NAMESPACE AXOpen.Io
    {S7.extern=ReadWrite}
    {#ix-attr:[Container(Layout.Wrap)]}
    CLASS PUBLIC AxoIOLinkET200SP_Balluff_IO_In
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#C1#>"}
            {#ix-attr:[ReadOnly()]}
            C1  :   AxoIOLinkET200SP_Balluff_IO_Port;            
            {#ix-set:AttributeName = "<#C2#>"}
            {#ix-attr:[ReadOnly()]}
            C2  :   AxoIOLinkET200SP_Balluff_IO_Port;            
            {#ix-set:AttributeName = "<#C3#>"}
            {#ix-attr:[ReadOnly()]}
            C3  :   AxoIOLinkET200SP_Balluff_IO_Port;            
            {#ix-set:AttributeName = "<#C4#>"}
            {#ix-attr:[ReadOnly()]}
            C4  :   AxoIOLinkET200SP_Balluff_IO_Port;            
        END_VAR 
    END_CLASS    
END_NAMESPACE