NAMESPACE AXOpen.Components.Kuka.Robotics
    TYPE
        HwIdentifiers : UINT
        (
            KRC4_HwID :=	UINT#258,
            KRC4_DIO512_512_digital_in__and_outputs_HwID :=	UINT#262,
            KRC4_KRC4_HwID :=	UINT#261,
            KRC4_KRC4_KRC4_ProfiNet_5_0_HwID :=	UINT#263,
            KRC4_KRC4_profinet_HwID :=	UINT#257,
            KRC4_KRC4_profinet_Port_1_HwID :=	UINT#259,
            KRC4_Rack_HwID :=	UINT#260,
            plc_line_HwID :=	UINT#32,
            plc_line_Rail_0_HwID :=	UINT#273,
            plc_line_plc_line_HwID :=	UINT#48,
            plc_line_plc_line_CPU_display_1_HwID :=	UINT#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=	UINT#51,
            plc_line_plc_line_DP_interface_1_HwID :=	UINT#60,
            plc_line_plc_line_OPC_UA_1_HwID :=	UINT#117,
            plc_line_plc_line_Virtual_communication_interface_HwID :=	UINT#135,
            plc_line_plc_line_profinet_x1_HwID :=	UINT#64,
            plc_line_plc_line_profinet_x1_Port_1_HwID :=	UINT#65,
            plc_line_plc_line_profinet_x1_Port_2_HwID :=	UINT#66,
            plc_line_plc_line_profinet_x2_HwID :=	UINT#72,
            plc_line_plc_line_profinet_x2_Port_3_HwID :=	UINT#73,
            profinet_plc_line_HwID :=	UINT#256,
    
            NONE := UINT#0
        );
    END_TYPE
END_NAMESPACE
