NAMESPACE AXOpen.Components.Rexroth.Press
    TYPE
        HwIdentifiers : UINT
        (
            plc_line_HwID :=UINT#32,
            plc_line_Rail_0_HwID :=UINT#268,
            plc_line_plc_line_HwID :=UINT#48,
            plc_line_plc_line_CPU_display_1_HwID :=UINT#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=UINT#51,
            plc_line_plc_line_DP_interface_1_HwID :=UINT#60,
            plc_line_plc_line_OPC_UA_1_HwID :=UINT#117,
            plc_line_plc_line_PROFINET_interface_1_HwID :=UINT#64,
            plc_line_plc_line_PROFINET_interface_1_Port_1_HwID :=UINT#65,
            plc_line_plc_line_PROFINET_interface_1_Port_2_HwID :=UINT#66,
            plc_line_plc_line_PROFINET_interface_2_HwID :=UINT#72,
            plc_line_plc_line_PROFINET_interface_2_Port_3_HwID :=UINT#73,
            plc_line_plc_line_Virtual_communication_interface_HwID :=UINT#135,
            profinet_plc_line_HwID :=UINT#256,
            rexroth_press_HwID :=UINT#258,
            rexroth_press_F_Modul_not_used_ID_FMod_NotUsed_HwID :=UINT#266,
            rexroth_press_Input_24_Words_ID_InMod_24Words_HwID :=UINT#264,
            rexroth_press_Output_21_Words_ID_OutMod_21Words_HwID :=UINT#263,
            rexroth_press_ParamCh_5Words_ID_PaCh_5Words_HwID :=UINT#265,
            rexroth_press_Rack_HwID :=UINT#261,
            rexroth_press_rexroth_press_HwID :=UINT#262,
            rexroth_press_rexroth_press_DAP_1_HwID :=UINT#267,
            rexroth_press_rexroth_press_PN_IO_HwID :=UINT#257,
            rexroth_press_rexroth_press_PN_IO_Port_1_HwID :=UINT#259,
            rexroth_press_rexroth_press_PN_IO_Port_2_HwID :=UINT#260,
    
            NONE := UINT#0
        );
    END_TYPE
END_NAMESPACE
