NAMESPACE AXOpen.Components.Rexroth.Press
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Outputs : STRUCT
            SFK_Output_21_Words_0 AT %B0:  WORD;
            SFK_Output_21_Words_1 AT %B2:  WORD;
            SFK_Output_21_Words_2 AT %B4:  WORD;
            SFK_Output_21_Words_3 AT %B6:  WORD;
            SFK_Output_21_Words_4 AT %B8:  WORD;
            SFK_Output_21_Words_5 AT %B10:  WORD;
            SFK_Output_21_Words_6 AT %B12:  WORD;
            SFK_Output_21_Words_7 AT %B14:  WORD;
            SFK_Output_21_Words_8 AT %B16:  WORD;
            SFK_Output_21_Words_9 AT %B18:  WORD;
            SFK_Output_21_Words_10 AT %B20:  WORD;
            SFK_Output_21_Words_11 AT %B22:  WORD;
            SFK_Output_21_Words_12 AT %B24:  WORD;
            SFK_Output_21_Words_13 AT %B26:  WORD;
            SFK_Output_21_Words_14 AT %B28:  WORD;
            SFK_Output_21_Words_15 AT %B30:  WORD;
            SFK_Output_21_Words_16 AT %B32:  WORD;
            SFK_Output_21_Words_17 AT %B34:  WORD;
            SFK_Output_21_Words_18 AT %B36:  WORD;
            SFK_Output_21_Words_19 AT %B38:  WORD;
            SFK_Output_21_Words_20 AT %B40:  WORD;
            SFK_ParamCh_5Words_0 AT %B42:  WORD;
            SFK_ParamCh_5Words_1 AT %B44:  WORD;
            SFK_ParamCh_5Words_2 AT %B46:  WORD;
            SFK_ParamCh_5Words_3 AT %B48:  WORD;
            SFK_ParamCh_5Words_4 AT %B50:  WORD;
        END_STRUCT;
    END_TYPE
END_NAMESPACE
