CONFIGURATION IoAddresses
    VAR_GLOBAL
        Axo_CS351_Input_2_word_1_InputAddress AT %ID0: DWORD;
        Axo_CS351_Input_4_word_1_InputAddress AT %IL124: LWORD;
        Axo_CS351_Input_4_word_10_InputAddress AT %IL52: LWORD;
        Axo_CS351_Input_4_word_11_InputAddress AT %IL44: LWORD;
        Axo_CS351_Input_4_word_12_InputAddress AT %IL36: LWORD;
        Axo_CS351_Input_4_word_13_InputAddress AT %IL28: LWORD;
        Axo_CS351_Input_4_word_14_InputAddress AT %IL20: LWORD;
        Axo_CS351_Input_4_word_15_InputAddress AT %IL12: LWORD;
        Axo_CS351_Input_4_word_16_InputAddress AT %IL4: LWORD;
        Axo_CS351_Input_4_word_2_InputAddress AT %IL116: LWORD;
        Axo_CS351_Input_4_word_3_InputAddress AT %IL108: LWORD;
        Axo_CS351_Input_4_word_4_InputAddress AT %IL100: LWORD;
        Axo_CS351_Input_4_word_5_InputAddress AT %IL92: LWORD;
        Axo_CS351_Input_4_word_6_InputAddress AT %IL84: LWORD;
        Axo_CS351_Input_4_word_7_InputAddress AT %IL76: LWORD;
        Axo_CS351_Input_4_word_8_InputAddress AT %IL68: LWORD;
        Axo_CS351_Input_4_word_9_InputAddress AT %IL60: LWORD;
        Axo_CS351_Output_2_word_1_OutputAddress AT %QD0: DWORD;
        Axo_CS351_Output_4_word_1_OutputAddress AT %QL60: LWORD;
        Axo_CS351_Output_4_word_2_OutputAddress AT %QL52: LWORD;
        Axo_CS351_Output_4_word_3_OutputAddress AT %QL44: LWORD;
        Axo_CS351_Output_4_word_4_OutputAddress AT %QL36: LWORD;
        Axo_CS351_Output_4_word_5_OutputAddress AT %QL28: LWORD;
        Axo_CS351_Output_4_word_6_OutputAddress AT %QL20: LWORD;
        Axo_CS351_Output_4_word_7_OutputAddress AT %QL12: LWORD;
        Axo_CS351_Output_4_word_8_OutputAddress AT %QL4: LWORD;

    END_VAR
END_CONFIGURATION
