NAMESPACE AXOpen.Components.Balluff.Identification
    TYPE
        HwIdentifiers : UINT
        (
            BNIPNT507005Z040_HwID :=	UINT#258,
            BNIPNT507005Z040_BIS_M_4XX_045_1_BIS_M_4XX_045_HwID :=	UINT#263,
            BNIPNT507005Z040_BNIPNT507005Z040_HwID :=	UINT#262,
            BNIPNT507005Z040_BNIPNT507005Z040_BNI_PNT_507_005_Z040_HwID :=	UINT#267,
            BNIPNT507005Z040_BNIPNT507005Z040_profinet_HwID :=	UINT#257,
            BNIPNT507005Z040_BNIPNT507005Z040_profinet_port_1___M12_HwID :=	UINT#259,
            BNIPNT507005Z040_BNIPNT507005Z040_profinet_port_2___M12_HwID :=	UINT#260,
            BNIPNT507005Z040_Rack_HwID :=	UINT#261,
            BNIPNT507005Z040_Standard_I_O_2_Standard_I_O_HwID :=	UINT#266,
            BNIPNT507005Z040_Standard_I_O_3_Standard_I_O_HwID :=	UINT#265,
            BNIPNT507005Z040_Standard_I_O_4_Standard_I_O_HwID :=	UINT#264,
            plc_line_HwID :=	UINT#32,
            plc_line_Rail_0_HwID :=	UINT#273,
            plc_line_plc_line_HwID :=	UINT#48,
            plc_line_plc_line_CPU_display_1_HwID :=	UINT#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=	UINT#51,
            plc_line_plc_line_DP_interface_1_HwID :=	UINT#60,
            plc_line_plc_line_OPC_UA_1_HwID :=	UINT#117,
            plc_line_plc_line_Virtual_communication_interface_HwID :=	UINT#135,
            plc_line_plc_line_profinet_x1_HwID :=	UINT#64,
            plc_line_plc_line_profinet_x1_Port_1_HwID :=	UINT#65,
            plc_line_plc_line_profinet_x1_Port_2_HwID :=	UINT#66,
            plc_line_plc_line_profinet_x2_HwID :=	UINT#72,
            plc_line_plc_line_profinet_x2_Port_3_HwID :=	UINT#73,
            profinet_plc_line_HwID :=	UINT#256,
    
            NONE := UINT#0
        );
    END_TYPE
END_NAMESPACE
