NAMESPACE AXOpen.Components.Balluff.Identification
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Outputs : STRUCT
            BNIPNT507005Z040_BIS_M_4XX_045_1_0 AT %B0:  WORD;
            BNIPNT507005Z040_BIS_M_4XX_045_1_1 AT %B2:  WORD;
            BNIPNT507005Z040_BIS_M_4XX_045_1_2 AT %B4:  WORD;
            BNIPNT507005Z040_BIS_M_4XX_045_1_3 AT %B6:  WORD;
            BNIPNT507005Z040_BIS_M_4XX_045_1_4 AT %B8:  WORD;
        END_STRUCT;
    END_TYPE
END_NAMESPACE
