NAMESPACE AXOpen.Components.Dukane.Welders
    {S7.extern=ReadWrite}
    {#ix-attr:[Container(Layout.Wrap)]}
    CLASS PUBLIC Axo_IQ_SeriesWelder_ProcessControlEnable
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#_0#>"}
            _0 : BOOL;   // bit24
            {#ix-set:AttributeName = "<#_1#>"}
            _1 : BOOL;   // bit25
            {#ix-set:AttributeName = "<#_2#>"}
            _2 : BOOL;   // bit26
            {#ix-set:AttributeName = "<#_3#>"}
            _3 : BOOL;   // bit27
            {#ix-set:AttributeName = "<#_4#>"}
            _4 : BOOL;   // bit28
            {#ix-set:AttributeName = "<#_5#>"}
            _5 : BOOL;   // bit29
            {#ix-set:AttributeName = "<#_6#>"}
            _6 : BOOL;   // bit30
            {#ix-set:AttributeName = "<#_7#>"}
            _7 : BOOL;   // bit31
            {#ix-set:AttributeName = "<#HoldTime_Enable#>"}
            HoldTime_Enable : BOOL;   // bit16
            {#ix-set:AttributeName = "<#Afterburst_Enable#>"}
            Afterburst_Enable : BOOL;   // bit17
            {#ix-set:AttributeName = "<#_10#>"}
            _10 : BOOL;   // bit18
            {#ix-set:AttributeName = "<#_11#>"}
            _11 : BOOL;   // bit19
            {#ix-set:AttributeName = "<#_12#>"}
            _12 : BOOL;   // bit20
            {#ix-set:AttributeName = "<#_13#>"}
            _13 : BOOL;   // bit21
            {#ix-set:AttributeName = "<#_14#>"}
            _14 : BOOL;   // bit22
            {#ix-set:AttributeName = "<#_15#>"}
            _15 : BOOL;   // bit23
            {#ix-set:AttributeName = "<#_16#>"}
            _16 : BOOL;   // bit8
            {#ix-set:AttributeName = "<#_17#>"}
            _17 : BOOL;   // bit9
            {#ix-set:AttributeName = "<#_18#>"}
            _18 : BOOL;   // bit10
            {#ix-set:AttributeName = "<#_19#>"}
            _19 : BOOL;   // bit11
            {#ix-set:AttributeName = "<#_20#>"}
            _20 : BOOL;   // bit12
            {#ix-set:AttributeName = "<#_21#>"}
            _21 : BOOL;   // bit13
            {#ix-set:AttributeName = "<#_22#>"}
            _22 : BOOL;   // bit14
            {#ix-set:AttributeName = "<#_23#>"}
            _23 : BOOL;   // bit15
            {#ix-set:AttributeName = "<#WeldTime_Enable#>"}
            WeldTime_Enable : BOOL;   // bit0
            {#ix-set:AttributeName = "<#WeldPower_Enable#>"}
            WeldPower_Enable : BOOL;   // bit1
            {#ix-set:AttributeName = "<#WeldEnergy_Enable#>"}
            WeldEnergy_Enable : BOOL;   // bit2
            {#ix-set:AttributeName = "<#WeldDistance_Enable#>"}
            WeldDistance_Enable : BOOL;   // bit3
            {#ix-set:AttributeName = "<#WeldPosition_Enable#>"}
            WeldPosition_Enable : BOOL;   // bit4
            {#ix-set:AttributeName = "<#_29#>"}
            _29 : BOOL;   // bit5
            {#ix-set:AttributeName = "<#_30#>"}
            _30 : BOOL;   // bit6
            {#ix-set:AttributeName = "<#_31#>"}
            _31 : BOOL;   // bit7      
        END_VAR 
    END_CLASS
END_NAMESPACE
