NAMESPACE AXOpen.Components.Dukane.Welders
    {S7.extern=ReadWrite}
    {#ix-attr:[Container(Layout.Wrap)]}
    CLASS PUBLIC Axo_IQ_SeriesWelder_ProcessLimitEnable_legacy
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#LowerBadEnergy#>"}
            LowerBadEnergy : BOOL;   // bit24
            {#ix-set:AttributeName = "<#LowerSuspectEnergy#>"}
            LowerSuspectEnergy : BOOL;   // bit25
            {#ix-set:AttributeName = "<#UpperSuspectEnergy#>"}
            UpperSuspectEnergy : BOOL;   // bit26
            {#ix-set:AttributeName = "<#UpperBadEnergy#>"}
            UpperBadEnergy : BOOL;   // bit27
            {#ix-set:AttributeName = "<#DisplayEnergy#>"}
            DisplayEnergy : BOOL;   // bit28
            {#ix-set:AttributeName = "<#_5#>"}
            _5 : BOOL;   // bit29
            {#ix-set:AttributeName = "<#_6#>"}
            _6 : BOOL;   // bit30
            {#ix-set:AttributeName = "<#_7#>"}
            _7 : BOOL;   // bit31
            {#ix-set:AttributeName = "<#LowerBadPower#>"}
            LowerBadPower : BOOL;   // bit16
            {#ix-set:AttributeName = "<#LowerSuspectPower#>"}
            LowerSuspectPower : BOOL;   // bit17
            {#ix-set:AttributeName = "<#UpperSuspectPower#>"}
            UpperSuspectPower : BOOL;   // bit18
            {#ix-set:AttributeName = "<#UpperBadPower#>"}
            UpperBadPower : BOOL;   // bit19
            {#ix-set:AttributeName = "<#DisplayPower#>"}
            DisplayPower : BOOL;   // bit20
            {#ix-set:AttributeName = "<#_13#>"}
            _13 : BOOL;   // bit21
            {#ix-set:AttributeName = "<#_14#>"}
            _14 : BOOL;   // bit22
            {#ix-set:AttributeName = "<#_15#>"}
            _15 : BOOL;   // bit23
            {#ix-set:AttributeName = "<#LowerBadTime#>"}
            LowerBadTime : BOOL;   // bit8
            {#ix-set:AttributeName = "<#LowerSuspectTime#>"}
            LowerSuspectTime : BOOL;   // bit9
            {#ix-set:AttributeName = "<#UpperSuspectTime#>"}
            UpperSuspectTime : BOOL;   // bit10
            {#ix-set:AttributeName = "<#UpperBadTIme#>"}
            UpperBadTIme : BOOL;   // bit11
            {#ix-set:AttributeName = "<#DisplayTime#>"}
            DisplayTime : BOOL;   // bit12
            {#ix-set:AttributeName = "<#_21#>"}
            _21 : BOOL;   // bit13
            {#ix-set:AttributeName = "<#_22#>"}
            _22 : BOOL;   // bit14
            {#ix-set:AttributeName = "<#_23#>"}
            _23 : BOOL;   // bit15
            {#ix-set:AttributeName = "<#_24#>"}
            _24 : BOOL;   // bit0
            {#ix-set:AttributeName = "<#_25#>"}
            _25 : BOOL;   // bit1
            {#ix-set:AttributeName = "<#_26#>"}
            _26 : BOOL;   // bit2
            {#ix-set:AttributeName = "<#_27#>"}
            _27 : BOOL;   // bit3
            {#ix-set:AttributeName = "<#_28#>"}
            _28 : BOOL;   // bit4
            {#ix-set:AttributeName = "<#_29#>"}
            _29 : BOOL;   // bit5
            {#ix-set:AttributeName = "<#_30#>"}
            _30 : BOOL;   // bit6
            {#ix-set:AttributeName = "<#_31#>"}
            _31 : BOOL;   // bit7      
        END_VAR 
    END_CLASS
END_NAMESPACE
