NAMESPACE AXOpen.Components.Cognex.Vision
	CLASS AxoVisionProHWIDs 
      VAR PUBLIC
         HW_System      : UINT;
         HW_Engine_1    : UINT;
         HW_Engine_2    : UINT;
         HW_Engine_3    : UINT;
         HW_Engine_4    : UINT;
         HW_UserData_1  : UINT;
         HW_UserData_2  : UINT;
         HW_UserData_3  : UINT;
         HW_UserData_4  : UINT;
         HW_UserData_5  : UINT;
         HW_UserData_6  : UINT;
         HW_Results_1   : UINT;
         HW_Results_2   : UINT;
         HW_Results_3   : UINT;
         HW_Results_4   : UINT;
         HW_Results_5   : UINT;
         HW_Results_6   : UINT;
      END_VAR
   END_CLASS
END_NAMESPACE
