<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <!-- Build Tools -->
  <ItemGroup>
    <GlobalPackageReference Include="GitVersion.MsBuild" Version="5.10.3" />
  </ItemGroup>
  <!-- Framework-Agnostic Packages -->
  <ItemGroup>
    <!-- AX# Libraries -->
    <PackageVersion Include="AXSharp.Abstractions" Version="0.47.0-alpha.431" />
    <PackageVersion Include="AXSharp.Connector" Version="0.47.0-alpha.431" />
    <PackageVersion Include="AXSharp.Connector.S71500.WebAPI" Version="0.47.0-alpha.431" />
    <PackageVersion Include="AXSharp.Presentation.Blazor" Version="0.47.0-alpha.431" />
    <PackageVersion Include="AXSharp.Presentation.Blazor.Controls" Version="0.47.0-alpha.431" />
    <PackageVersion Include="Inxton.Operon" Version="0.3.0-alpha.113" />
    <!-- Data & Serialization -->
    <PackageVersion Include="ClosedXML" Version="0.105.0" />
    <PackageVersion Include="Microsoft.Build" Version="18.0.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="MongoDB.Bson" Version="3.5.2" />
    <PackageVersion Include="MongoDB.Driver" Version="3.5.2" />
    <PackageVersion Include="MongoDB.Driver.Core" Version="2.30.0" />
    <PackageVersion Include="NuGet.Packaging" Version="6.14.0" />
    <PackageVersion Include="RavenDB.Client" Version="7.1.4" />
    <PackageVersion Include="RavenDB.Embedded" Version="7.1.4" />
    <!-- UI & Presentation -->
    <PackageVersion Include="AXOpen.KristofferStrube.Blazor.SVGEditor" Version="0.4.4-alpha.298" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <!-- Utilities -->
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="Cocona" Version="2.2.0" />
    <PackageVersion Include="Humanizer" Version="3.0.1" />
    <PackageVersion Include="K4os.Hash.xxHash" Version="1.0.8" />
    <PackageVersion Include="SSH.NET" Version="2025.1.0" />
    <!-- Logging -->
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <!-- Hardware & Devices -->
    <PackageVersion Include="Siemens.Simatic.S7.Webserver.API" Version="3.3.3" />
    <!-- Testing - Core -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <!-- Testing - MSTest -->
    <PackageVersion Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.0.2" />
    <!-- Testing - NUnit -->
    <PackageVersion Include="nunit" Version="4.4.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.2.0" />
    <!-- Testing - xUnit -->
    <PackageVersion Include="System.IO.Packaging" Version="8.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <!-- Testing - Reporting -->
    <PackageVersion Include="JunitXml.TestLogger" Version="7.0.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <!-- Build & Packaging -->
    <PackageVersion Include="Microsoft.NET.ILLink.Tasks" Version="9.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageVersion Include="CliWrap" Version="3.6.7" />
    <PackageVersion Include="Octokit" Version="8.0.0" />
    <PackageVersion Include="Octokit.Extensions" Version="1.0.7" />
    <PackageVersion Include="Cake.Frosting" Version="4.0.0" />
    <PackageVersion Include="Cake.Powershell" Version="4.0.0" />
    <PackageVersion Include="Polly" Version="8.5.0" />
    <PackageVersion Include="YamlDotNet" Version="16.2.0" />
    <!-- Target Framework Specific Packages -->
    <!-- AspNetCore -->
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
    <!-- Entity Framework -->
    <PackageVersion Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
    <!-- Identity -->
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Stores" Version="10.0.0" />
    <!-- Extensions -->
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.0-rc.1.25458.5" />

    <PackageVersion Include="Microsoft.Build.Tasks.Core" Version="18.0.2" />
  </ItemGroup>
</Project>










