// NAMESPACE AXOpen.Components.Dukane.Welders
//     {S7.extern=ReadWrite}
//     {#ix-attr:[Container(Layout.Wrap)]}
//     CLASS PUBLIC Axo_IQ_SeriesWelder_Record
//         VAR PUBLIC 
//             {#ix-set:AttributeName = "<#Valid#>"}
//             Valid               : BOOL;
//             {#ix-set:AttributeName = "<#Done#>"}
//             Done                : BOOL;
//             {#ix-set:AttributeName = "<#Busy#>"}
//             Busy                : BOOL;
//             {#ix-set:AttributeName = "<#Error#>"}
//             Error               : BOOL;
//             {#ix-set:AttributeName = "<#_To_iQ#>"}
//             _To_iQ              : BOOL;
//             {#ix-set:AttributeName = "<#_From_iQ#>"}
//             _From_iQ            : BOOL;
//             {#ix-set:AttributeName = "<#On_Pwr_Up#>"}
//             On_Pwr_Up           : BOOL;   // Set on rack/station exist, activate and not failed
//             {#ix-set:AttributeName = "<#Wr_Rd#>"}
//             Wr_Rd               : BOOL;
//             {#ix-set:AttributeName = "<#Alarm#>"}
//             Alarm               : BOOL;   // Display HMI alarm message.
//             {#ix-set:AttributeName = "<#Len#>"}
//             Len                 : INT;
//             {#ix-set:AttributeName = "<#MLen#>"}
//             MLen                : INT;
//             {#ix-set:AttributeName = "<#Status#>"}
//             Status              : DWORD;
//             {#ix-set:AttributeName = "<#ErrorCode#>"}
//             ErrorCode           : DWORD;
//             {#ix-set:AttributeName = "<#ErrorType#>"}
//             ErrorType           : DWORD;
//             {#ix-set:AttributeName = "<#Parameter_Index#>"}
//             Parameter_Index     : DWORD;            
//         END_VAR 
//     END_CLASS    
// END_NAMESPACE