NAMESPACE AXOpen.Components.Dukane.Welders
    {S7.extern=ReadWrite}
    {#ix-attr:[Container(Layout.Wrap)]}
    CLASS PUBLIC Axo_IQ_SeriesWelder_CopySetup
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#Destination_Setup#>"}
            Destination_Setup   :	INT;
            {#ix-set:AttributeName = "<#Source_Setup#>"}
            Source_Setup        :	INT;
        END_VAR 
    END_CLASS   
END_NAMESPACE
