//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXOpen.Components.Balluff.Identification.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlcStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlcStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AXOpen.Components.Balluff.Identification.Resources.PlcStringResources", typeof(PlcStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadTask timeout..
        /// </summary>
        public static string ReadTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("ReadTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetCommunicationTask timeout..
        /// </summary>
        public static string ResetCommunicationTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("ResetCommunicationTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetReaderTask timeout..
        /// </summary>
        public static string ResetReaderTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("ResetReaderTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteCharToMemoryTask timeout..
        /// </summary>
        public static string WriteCharToMemoryTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("WriteCharToMemoryTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteTask timeout..
        /// </summary>
        public static string WriteTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("WriteTask_timeout_DOT_", resourceCulture);
            }
        }
    }
}
