using AXOpen.Data;

NAMESPACE AxoDataExamples

    CLASS AxoTestDataStructure
        VAR PUBLIC
            RecipeName : STRING;
            String1 : STRING;
            Int1 : INT;
            Bool1 : BOOL;
            String2 : STRING;
            Int2 : INT;
            Bool2 : BOOL;
            String3 : STRING;
            Int3 : INT;
            Bool3 : BOOL;
        END_VAR 
    END_CLASS    
END_NAMESPACE