NAMESPACE AXOpen.Components.Dukane.Welders
    {S7.extern=ReadWrite}
    {#ix-attr:[Container(Layout.Wrap)]}
    CLASS PUBLIC Axo_IQ_SeriesWelder_ProcessErrorStatus
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#_0#>"}
            _0 : BOOL;
            {#ix-set:AttributeName = "<#_1#>"}
            _1 : BOOL;
            {#ix-set:AttributeName = "<#_2#>"}
            _2 : BOOL;
            {#ix-set:AttributeName = "<#_3#>"}
            _3 : BOOL;
            {#ix-set:AttributeName = "<#_4#>"}
            _4 : BOOL;
            {#ix-set:AttributeName = "<#_5#>"}
            _5 : BOOL;
            {#ix-set:AttributeName = "<#_6#>"}
            _6 : BOOL;
            {#ix-set:AttributeName = "<#_7#>"}
            _7 : BOOL;
            {#ix-set:AttributeName = "<#_8#>"}
            _8 : BOOL;
            {#ix-set:AttributeName = "<#_9#>"}
            _9 : BOOL;
            {#ix-set:AttributeName = "<#_10#>"}
            _10 : BOOL;
            {#ix-set:AttributeName = "<#_11#>"}
            _11 : BOOL;
            {#ix-set:AttributeName = "<#_12#>"}
            _12 : BOOL;
            {#ix-set:AttributeName = "<#_13#>"}
            _13 : BOOL;
            {#ix-set:AttributeName = "<#_14#>"}
            _14 : BOOL;
            {#ix-set:AttributeName = "<#_15#>"}
            _15 : BOOL;
            {#ix-set:AttributeName = "<#Trigger_Delay#>"}
            Trigger_Delay : BOOL;
            {#ix-set:AttributeName = "<#Servo_DN_Limit#>"}
            Servo_DN_Limit : BOOL;
            {#ix-set:AttributeName = "<#Servo_TOS_Position#>"}
            Servo_TOS_Position : BOOL;
            {#ix-set:AttributeName = "<#_19#>"}
            _19 : BOOL;
            {#ix-set:AttributeName = "<#_20#>"}
            _20 : BOOL;
            {#ix-set:AttributeName = "<#_21#>"}
            _21 : BOOL;
            {#ix-set:AttributeName = "<#_22#>"}
            _22 : BOOL;
            {#ix-set:AttributeName = "<#_23#>"}
            _23 : BOOL;
            {#ix-set:AttributeName = "<#Forced_ShutDown#>"}
            Forced_ShutDown : BOOL;
            {#ix-set:AttributeName = "<#Trigger_Lost_Early#>"}
            Trigger_Lost_Early : BOOL;
            {#ix-set:AttributeName = "<#Trigger_Lost_Weld#>"}
            Trigger_Lost_Weld : BOOL;
            {#ix-set:AttributeName = "<#Latched_Bad_Part#>"}
            Latched_Bad_Part : BOOL;
            {#ix-set:AttributeName = "<#PreTrigger_OverTravel#>"}
            PreTrigger_OverTravel : BOOL;
            {#ix-set:AttributeName = "<#Part_Detected#>"}
            Part_Detected : BOOL;
            {#ix-set:AttributeName = "<#PreTrigger_Time#>"}
            PreTrigger_Time : BOOL;
            {#ix-set:AttributeName = "<#Trigger_Time#>"}
            Trigger_Time : BOOL;
        END_VAR 
    END_CLASS    
END_NAMESPACE