flowchart TD
    classDef states fill:#80FF00,stroke:#0080FF,stroke-width:4px,color:#7F00FF,font-size:15px,font-weight:bold                                                      
    classDef actions fill:#ff8000,stroke:#0080ff,stroke-width:4px,color:#7F00FF,font-size:15px,font-weight:bold                                                      

    s1((Ready))
    s2((Kicking))
    s3((Busy))
    s4((Done))
    s5((Error))
    a1("Invoke()#128258;")
    a2("Execute()#128260;")
    a3("DoneWhen(TRUE)#128258;")
    a4("ThrowWhen(TRUE)#128258;")
    a5("NOT Invoke() call for at least two Context cycles#128260;")
    a6("Restore()#128258;")

    subgraph  
        s1:::states --> a1:::actions --> s2:::states --> a2:::actions --> s3:::states --> a3:::actions --> s4:::states --> a5:::actions --> a1:::actions
    end
    subgraph   
        s3:::states --> a4:::actions
        a4:::actions --> s5:::states --> a6:::actions --> s1:::states 
    end

    subgraph   
        s((State)):::states
        ac("Action #128260;:called cyclically"):::actions
        as("Action #128258;:single or cyclical call "):::actions
    end
