TYPE
	HwIdentifiers : WORD
	(
		PLC_LINE_Rail_0 :=	WORD#256,
		PLC_LINE :=	WORD#48,
		PLC_LINE_Card_reader_writer_1 :=	WORD#51,
		PLC_LINE_CPU_display_1 :=	WORD#54,
		PLC_LINE_OPC_UA_1 :=	WORD#117,
		PLC_LINE_PROFINET_interface_1 :=	WORD#64,
		PLC_LINE_PROFINET_interface_1_Port_1 :=	WORD#65,
		PLC_LINE_PROFINET_interface_1_Port_2 :=	WORD#66,
		PLC_LINE_PROFINET_interface_2 :=	WORD#72,
		PLC_LINE_PROFINET_interface_2_Port_1 :=	WORD#73,
		PLC_LINE_DP_interface_1 :=	WORD#60,
		PLC_LINE_PROFINET_interface_GBIT_3 :=	WORD#120,
		PLC_LINE_PROFINET_interface_GBIT_3_Port_1 :=	WORD#121,
		wp462_t1_rh_deso_Rack :=	WORD#331,
		wp462_t1_rh_deso :=	WORD#332,
		wp462_t1_rh_deso_Interface :=	WORD#333,
		wp462_t1_rh_deso_Interface_Port_1 :=	WORD#334,
		wp462_t1_rh_deso_RT :=	WORD#335,
		wp462_t1_rh_deso_Input_1_byte_1 :=	WORD#262,
		wp462_t1_rh_deso_Input_1_byte_2 :=	WORD#263,
		wp462_t1_rh_deso_Input_2_word_1 :=	WORD#264,
		wp462_t1_rh_deso_Input_1_word_1 :=	WORD#265,
		wp462_t1_rh_deso_Input_2_word_2 :=	WORD#266,
		wp462_t1_rh_deso_Input_1_word_2 :=	WORD#258,
		wp462_t1_rh_deso_Output_1_byte_1 :=	WORD#259,
		wp462_t1_rh_deso_Output_1_byte_2 :=	WORD#260,
		NONE:= WORD#0
	);
END_TYPE
