NAMESPACE AXOpen.Components.Abstractions.Robotics
    {S7.extern=ReadWrite}
    CLASS PUBLIC AxoRoboticsBasicCoordinates
        VAR PUBLIC
            {#ix-set:AttributeName = "<#Coordinate X#>"}
            X : REAL;
            {#ix-set:AttributeName = "<#Coordinate Y#>"}
            Y : REAL;
            {#ix-set:AttributeName = "<#Coordinate Z#>"}
            Z : REAL;
        END_VAR
    END_CLASS
END_NAMESPACE