NAMESPACE AXOpen.Components.Abstractions.Robotics
    TYPE AxoRoboticsCoordinates : STRUCT
            {#ix-set:AttributeName = "<#Coordinate X#>"}
            X : REAL;
            {#ix-set:AttributeName = "<#Coordinate Y#>"}
            Y : REAL;
            {#ix-set:AttributeName = "<#Coordinate Z#>"}
            Z : REAL;
            {#ix-set:AttributeName = "<#Coordinate Rx#>"}
            Rx : REAL;
            {#ix-set:AttributeName = "<#Coordinate Ry#>"}
            Ry : REAL;
            {#ix-set:AttributeName = "<#Coordinate Rz#>"}
            Rz : REAL;
        END_STRUCT;
    END_TYPE
END_NAMESPACE