<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AXOpen.Dev</RootNamespace>
    <AssemblyName>AXOpen.Dev</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="CliWrap" />
  </ItemGroup>

</Project>
