<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>AXOpen.Data.Blazor</PackageId>
    <RootNamespace>AXOpen.Data.Blazor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />    
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\core\src\AXOpen.Core.Blazor\axopen_core_blazor.csproj" />
    <ProjectReference Include="..\..\..\Security\src\AXOpen.Security\AXOpen.Security.csproj" />
    <ProjectReference Include="..\AXOpen.Data\inxton_axopen_data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\AxOpenDataResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AxOpenDataResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\AxOpenDataResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AxOpenDataResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<None Include="AxoDataExchange\**\*.*" Exclude="AxoDataExchange\**\*.js;AxoDataExchange\**\*.css" Pack="true" PackagePath="contentFiles\AxoDataExchange\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="DataPersistentExchange\**\*.*" Exclude="DataPersistentExchange\**\*.js;DataPersistentExchange\**\*.css" Pack="true" PackagePath="contentFiles\DataPersistentExchange\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="Distributed\**\*.*" Exclude="Distributed\**\*.js;Distributed\**\*.css" Pack="true" PackagePath="contentFiles\Distributed\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="build\AXOpen.Data.Blazor.targets" Pack="true" PackagePath="build\AXOpen.Data.Blazor.targets" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<PropertyGroup>
		<DefaultItemExcludes>$(DefaultItemExcludes);temp\**\*</DefaultItemExcludes>
	</PropertyGroup>

</Project>
