CONFIGURATION IoAddresses
    VAR_GLOBAL

        // Module et200sp_1/A10
        et200sp_1_A10_Input AT %IB22 : et200sp_1_A10_Input_Layout;

        // Module et200sp_1/A11
        et200sp_1_A11_Input AT %IB20 : et200sp_1_A11_Input_Layout;

        // Module et200sp_1/A12
        et200sp_1_A12_Input AT %IB18 : et200sp_1_A12_Input_Layout;

        // Module et200sp_1/A13
        et200sp_1_A13_Input AT %IB16 : et200sp_1_A13_Input_Layout;

        // Module et200sp_1/A14
        et200sp_1_A14_Input AT %IB14 : et200sp_1_A14_Input_Layout;

        // Module et200sp_1/A15
        et200sp_1_A15_Input AT %IB12 : et200sp_1_A15_Input_Layout;

        // Module et200sp_1/A16
        et200sp_1_A16_Input AT %IB10 : et200sp_1_A16_Input_Layout;

        // Module et200sp_1/A17
        et200sp_1_A17_Input AT %IB8 : et200sp_1_A17_Input_Layout;

        // Module et200sp_1/A20
        et200sp_1_A20_Output AT %QB14 : et200sp_1_A20_Output_Layout;

        // Module et200sp_1/A21
        et200sp_1_A21_Output AT %QB12 : et200sp_1_A21_Output_Layout;

        // Module et200sp_1/A22
        et200sp_1_A22_Output AT %QB10 : et200sp_1_A22_Output_Layout;

        // Module et200sp_1/A23
        et200sp_1_A23_Output AT %QB8 : et200sp_1_A23_Output_Layout;

        // Module et200sp_1/A30
        et200sp_1_A30_Input AT %IB0 : et200sp_1_A30_Input_Layout;

        // Module et200sp_1/A40
        et200sp_1_A40_Output AT %QB0 : et200sp_1_A40_Output_Layout;
    END_VAR
END_CONFIGURATION

TYPE
    et200sp_1_A10_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A11_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A12_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A13_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A14_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A15_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A16_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A17_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A20_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A21_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A22_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A23_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.3 : BOOL;
        Signals_12 AT %X1.4 : BOOL;
        Signals_13 AT %X1.5 : BOOL;
        Signals_14 AT %X1.6 : BOOL;
        Signals_15 AT %X1.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A30_Input_Layout : STRUCT
        Signals_0 AT %B0 : INT;
        Signals_1 AT %B2 : INT;
        Signals_2 AT %B4 : INT;
        Signals_3 AT %B6 : INT;
    END_STRUCT;
END_TYPE

TYPE
    et200sp_1_A40_Output_Layout : STRUCT
        Signals_0 AT %B0 : INT;
        Signals_1 AT %B2 : INT;
        Signals_2 AT %B4 : INT;
        Signals_3 AT %B6 : INT;
    END_STRUCT;
END_TYPE
