<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>AXOpen.Core.Blazor</PackageId>
    <RootNamespace>AXOpen.Core.Blazor</RootNamespace>
  </PropertyGroup>

 

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />   
		<PackageReference Include="AXSharp.Presentation.Blazor" />
	    <PackageReference Include="AXSharp.Presentation.Blazor.Controls" />
	    <PackageReference Include="Humanizer" />
	    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
	    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\..\..\..\..\..\..\operon\src\Operon\Operon.csproj" /> -->
	  <ProjectReference Include="..\..\..\base\src\AXOpen.VisualComposer\AXOpen.VisualComposer.csproj" />
	  <ProjectReference Include="..\AXOpen.Core\inxton_axopen_core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\AxOpenCoreResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AxOpenCoreResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\StringResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>StringResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\AxOpenCoreResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AxOpenCoreResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\StringResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>StringResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<None Include="AxoAlert\**\*.*" Exclude="AxoAlert\**\*.js;AxoAlert\**\*.css" Pack="true" PackagePath="contentFiles\AxoAlert\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoArrays\**\*.*" Exclude="AxoArrays\**\*.js;AxoArrays\**\*.css" Pack="true" PackagePath="contentFiles\AxoArrays\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoComponent\**\*.*" Exclude="AxoComponent\**\*.js;AxoComponent\**\*.css" Pack="true" PackagePath="contentFiles\AxoComponent\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoCoordination\**\*.*" Exclude="AxoCoordination\**\*.js;AxoCoordination\**\*.css" Pack="true" PackagePath="contentFiles\AxoCoordination\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoDialogContainer\**\*.*" Exclude="AxoDialogContainer\**\*.js;AxoDialogContainer\**\*.css" Pack="true" PackagePath="contentFiles\AxoDialogContainer\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoDialogs\**\*.*" Exclude="AxoDialogs\**\*.js;AxoDialogs\**\*.css" Pack="true" PackagePath="contentFiles\AxoDialogs\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoLocator\**\*.*" Exclude="AxoLocator\**\*.js;AxoLocator\**\*.css" Pack="true" PackagePath="contentFiles\AxoLocator\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoMessenger\**\*.*" Exclude="AxoMessenger\**\*.js;AxoMessenger\**\*.css" Pack="true" PackagePath="contentFiles\AxoMessenger\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoMomentaryTask\**\*.*" Exclude="AxoMomentaryTask\**\*.js;AxoMomentaryTask\**\*.css" Pack="true" PackagePath="contentFiles\AxoMomentaryTask\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoObject\**\*.*" Exclude="AxoObject\**\*.js;AxoObject\**\*.css" Pack="true" PackagePath="contentFiles\AxoObject\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoTask\**\*.*" Exclude="AxoTask\**\*.js;AxoTask\**\*.css" Pack="true" PackagePath="contentFiles\AxoTask\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoTextList\**\*.*" Exclude="AxoTextList\**\*.js;AxoTextList\**\*.css" Pack="true" PackagePath="contentFiles\AxoTextList\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="AxoToggleTask\**\*.*" Exclude="AxoToggleTask\**\*.js;AxoToggleTask\**\*.css" Pack="true" PackagePath="contentFiles\AxoToggleTask\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="build\AXOpen.Core.Blazor.targets" Pack="true" PackagePath="build\AXOpen.Core.Blazor.targets" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<PropertyGroup>
		<DefaultItemExcludes>$(DefaultItemExcludes);temp\**\*</DefaultItemExcludes>
	</PropertyGroup>
</Project>
