## YamlMime:ManagedReference
items:
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config
  parent: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children:
  - plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.InfoTime
  - plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.ErrorTime
  - plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.MaxJobNumber
  name: AxoInsight_Config
  fullName: AxoInsight_Config
  type: Struct
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config
    path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
    startLine: 2
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: STRUCT AxoInsight_Config
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.InfoTime
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.InfoTime
  parent: AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children: []
  name: InfoTime
  fullName: InfoTime
  type: Property
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.InfoTime
    path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
    startLine: 5
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: 'InfoTime : LTIME'
    return:
      type: LTIME
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.ErrorTime
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.ErrorTime
  parent: AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children: []
  name: ErrorTime
  fullName: ErrorTime
  type: Property
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.ErrorTime
    path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
    startLine: 7
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: 'ErrorTime : LTIME'
    return:
      type: LTIME
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.MaxJobNumber
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.MaxJobNumber
  parent: AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children: []
  name: MaxJobNumber
  fullName: MaxJobNumber
  type: Property
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoInsight_Config.MaxJobNumber
    path: .\src\components.cognex.vision\ctrl\src\AxoInsight\v_6_0_0\TypeStructuresAndEnums\AxoInsight_Config.st
    startLine: 9
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: 'MaxJobNumber : UINT'
    return:
      type: UINT
references:
- uid: plc.LTIME
  name: LTIME
  nameWithType: LTIME
  fullName: LTIME
- uid: plc.UINT
  name: UINT
  nameWithType: UINT
  fullName: UINT


