## YamlMime:ManagedReference
items:
- uid: plc.AXOpen.Elements.AxoAiConfig
  id: plc.AXOpen.Elements.AxoAiConfig
  parent: plc.AXOpen.Elements
  children:
  - plc.AXOpen.Elements.AxoAiConfig.RawLow
  - plc.AXOpen.Elements.AxoAiConfig.RawHigh
  - plc.AXOpen.Elements.AxoAiConfig.RealLow
  - plc.AXOpen.Elements.AxoAiConfig.RealHigh
  - plc.AXOpen.Elements.AxoAiConfig.Gain
  - plc.AXOpen.Elements.AxoAiConfig.Offset
  name: AxoAiConfig
  fullName: AxoAiConfig
  type: Class
  source:
    remote:
      path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Elements.AxoAiConfig
    path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
    startLine: 5
  namespace: plc.AXOpen.Elements
  syntax:
    content: CLASS AxoAiConfig
  inheritance: &o0 []
  inheritedMembers: *o0
  implements: *o0
- uid: plc.AXOpen.Elements.AxoAiConfig.RawLow
  id: plc.AXOpen.Elements.AxoAiConfig.RawLow
  parent: AXOpen.Elements
  children: []
  name: RawLow
  fullName: RawLow
  type: Property
  source:
    remote:
      path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Elements.AxoAiConfig.RawLow
    path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
    startLine: 13
  namespace: plc.AXOpen.Elements
  syntax:
    content: 'RawLow : DINT'
    return:
      type: DINT
- uid: plc.AXOpen.Elements.AxoAiConfig.RawHigh
  id: plc.AXOpen.Elements.AxoAiConfig.RawHigh
  parent: AXOpen.Elements
  children: []
  name: RawHigh
  fullName: RawHigh
  type: Property
  source:
    remote:
      path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Elements.AxoAiConfig.RawHigh
    path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
    startLine: 18
  namespace: plc.AXOpen.Elements
  syntax:
    content: 'RawHigh : DINT'
    return:
      type: DINT
- uid: plc.AXOpen.Elements.AxoAiConfig.RealLow
  id: plc.AXOpen.Elements.AxoAiConfig.RealLow
  parent: AXOpen.Elements
  children: []
  name: RealLow
  fullName: RealLow
  type: Property
  source:
    remote:
      path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Elements.AxoAiConfig.RealLow
    path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
    startLine: 25
  namespace: plc.AXOpen.Elements
  syntax:
    content: 'RealLow : REAL'
    return:
      type: REAL
- uid: plc.AXOpen.Elements.AxoAiConfig.RealHigh
  id: plc.AXOpen.Elements.AxoAiConfig.RealHigh
  parent: AXOpen.Elements
  children: []
  name: RealHigh
  fullName: RealHigh
  type: Property
  source:
    remote:
      path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Elements.AxoAiConfig.RealHigh
    path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
    startLine: 31
  namespace: plc.AXOpen.Elements
  syntax:
    content: 'RealHigh : REAL'
    return:
      type: REAL
- uid: plc.AXOpen.Elements.AxoAiConfig.Gain
  id: plc.AXOpen.Elements.AxoAiConfig.Gain
  parent: AXOpen.Elements
  children: []
  name: Gain
  fullName: Gain
  type: Property
  source:
    remote:
      path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Elements.AxoAiConfig.Gain
    path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
    startLine: 35
  namespace: plc.AXOpen.Elements
  syntax:
    content: 'Gain : REAL'
    return:
      type: REAL
- uid: plc.AXOpen.Elements.AxoAiConfig.Offset
  id: plc.AXOpen.Elements.AxoAiConfig.Offset
  parent: AXOpen.Elements
  children: []
  name: Offset
  fullName: Offset
  type: Property
  source:
    remote:
      path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
      branch: 209-_NEW-FEATURE_Create_library_for_Rexroth_drives
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Elements.AxoAiConfig.Offset
    path: .\src\components.elements\ctrl\src\AxoAi\AxoAiConfig.st
    startLine: 40
  namespace: plc.AXOpen.Elements
  syntax:
    content: 'Offset : REAL'
    return:
      type: REAL
references:
- uid: plc.DINT
  name: DINT
  nameWithType: DINT
  fullName: DINT
- uid: plc.REAL
  name: REAL
  nameWithType: REAL
  fullName: REAL


