## YamlMime:ManagedReference
items:
- uid: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config
  id: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config
  parent: plc.AXOpen.Components.Siem.Identification
  children:
  - plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.InfoTime
  - plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.ErrorTime
  name: AxoIOLink_RF200Device_Config
  fullName: AxoIOLink_RF200Device_Config
  type: Class
  source:
    remote:
      path: .\src\components.siem.identification\ctrl\src\IOLink\AxoIOLinkRF200DataTypes\AxoIOLink_RF200Device_Config.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config
    path: .\src\components.siem.identification\ctrl\src\IOLink\AxoIOLinkRF200DataTypes\AxoIOLink_RF200Device_Config.st
    startLine: 0
  namespace: plc.AXOpen.Components.Siem.Identification
  syntax:
    content: CLASS AxoIOLink_RF200Device_Config
  inheritance: &o0 []
  inheritedMembers: *o0
  implements: *o0
- uid: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.InfoTime
  id: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.InfoTime
  parent: AXOpen.Components.Siem.Identification
  children: []
  name: InfoTime
  fullName: InfoTime
  type: Property
  source:
    remote:
      path: .\src\components.siem.identification\ctrl\src\IOLink\AxoIOLinkRF200DataTypes\AxoIOLink_RF200Device_Config.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.InfoTime
    path: .\src\components.siem.identification\ctrl\src\IOLink\AxoIOLinkRF200DataTypes\AxoIOLink_RF200Device_Config.st
    startLine: 5
  namespace: plc.AXOpen.Components.Siem.Identification
  syntax:
    content: 'InfoTime : LTIME'
    return:
      type: LTIME
- uid: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.ErrorTime
  id: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.ErrorTime
  parent: AXOpen.Components.Siem.Identification
  children: []
  name: ErrorTime
  fullName: ErrorTime
  type: Property
  source:
    remote:
      path: .\src\components.siem.identification\ctrl\src\IOLink\AxoIOLinkRF200DataTypes\AxoIOLink_RF200Device_Config.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Siem.Identification.AxoIOLink_RF200Device_Config.ErrorTime
    path: .\src\components.siem.identification\ctrl\src\IOLink\AxoIOLinkRF200DataTypes\AxoIOLink_RF200Device_Config.st
    startLine: 7
  namespace: plc.AXOpen.Components.Siem.Identification
  syntax:
    content: 'ErrorTime : LTIME'
    return:
      type: LTIME
references:
- uid: plc.LTIME
  name: LTIME
  nameWithType: LTIME
  fullName: LTIME


