## YamlMime:ManagedReference
items:
- uid: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x
  id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x
  parent: plc.AXOpen.Components.Abb.Robotics
  children:
  - plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.InfoTime
  - plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.ErrorTime
  - plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.TaskTimeout
  - plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.HWIDs
  name: AxoAbbRobotics_Config_v_1_x_x
  fullName: AxoAbbRobotics_Config_v_1_x_x
  type: Class
  source:
    remote:
      path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x
    path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
    startLine: 0
  namespace: plc.AXOpen.Components.Abb.Robotics
  syntax:
    content: CLASS AxoAbbRobotics_Config_v_1_x_x
  inheritance: &o0 []
  inheritedMembers: *o0
  implements: *o0
- uid: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.InfoTime
  id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.InfoTime
  parent: AXOpen.Components.Abb.Robotics
  children: []
  name: InfoTime
  fullName: InfoTime
  type: Property
  source:
    remote:
      path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.InfoTime
    path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
    startLine: 5
  namespace: plc.AXOpen.Components.Abb.Robotics
  syntax:
    content: 'InfoTime : LTIME'
    return:
      type: LTIME
- uid: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.ErrorTime
  id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.ErrorTime
  parent: AXOpen.Components.Abb.Robotics
  children: []
  name: ErrorTime
  fullName: ErrorTime
  type: Property
  source:
    remote:
      path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.ErrorTime
    path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
    startLine: 7
  namespace: plc.AXOpen.Components.Abb.Robotics
  syntax:
    content: 'ErrorTime : LTIME'
    return:
      type: LTIME
- uid: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.TaskTimeout
  id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.TaskTimeout
  parent: AXOpen.Components.Abb.Robotics
  children: []
  name: TaskTimeout
  fullName: TaskTimeout
  type: Property
  source:
    remote:
      path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.TaskTimeout
    path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
    startLine: 9
  namespace: plc.AXOpen.Components.Abb.Robotics
  syntax:
    content: 'TaskTimeout : LTIME'
    return:
      type: LTIME
- uid: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.HWIDs
  id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.HWIDs
  parent: AXOpen.Components.Abb.Robotics
  children: []
  name: HWIDs
  fullName: HWIDs
  type: Property
  source:
    remote:
      path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
      branch: dev
      repo: https://github.com/Inxton/AXOpen.git
    id: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_Config_v_1_x_x.HWIDs
    path: .\src\components.abb.robotics\ctrl\src\AxoAbbRobotics_Config_v_1_x_x.st
    startLine: 11
  namespace: plc.AXOpen.Components.Abb.Robotics
  syntax:
    content: 'HWIDs : AXOpen.Components.Abb.Robotics.AxoAbbRobotics_HWIDs'
    return:
      type: AXOpen.Components.Abb.Robotics.AxoAbbRobotics_HWIDs
references:
- uid: plc.LTIME
  name: LTIME
  nameWithType: LTIME
  fullName: LTIME
- uid: plc.AXOpen.Components.Abb.Robotics.AxoAbbRobotics_HWIDs
  name: AxoAbbRobotics_HWIDs
  nameWithType: AxoAbbRobotics_HWIDs
  fullName: AXOpen.Components.Abb.Robotics.AxoAbbRobotics_HWIDs


