## YamlMime:ManagedReference
items:
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config
  parent: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children:
  - plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ContinuousReading
  - plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.InfoTime
  - plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ErrorTime
  name: AxoDataman_Config
  fullName: AxoDataman_Config
  type: Struct
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
      branch: 293-Festo_CMMT-AS_class_not_derived_from_AxoDrive_just_point_to_point_movements
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config
    path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
    startLine: 2
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: STRUCT AxoDataman_Config
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ContinuousReading
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ContinuousReading
  parent: AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children: []
  name: ContinuousReading
  fullName: ContinuousReading
  type: Property
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
      branch: 293-Festo_CMMT-AS_class_not_derived_from_AxoDrive_just_point_to_point_movements
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ContinuousReading
    path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
    startLine: 6
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: 'ContinuousReading : BOOL'
    return:
      type: BOOL
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.InfoTime
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.InfoTime
  parent: AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children: []
  name: InfoTime
  fullName: InfoTime
  type: Property
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
      branch: 293-Festo_CMMT-AS_class_not_derived_from_AxoDrive_just_point_to_point_movements
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.InfoTime
    path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
    startLine: 8
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: 'InfoTime : LTIME'
    return:
      type: LTIME
- uid: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ErrorTime
  id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ErrorTime
  parent: AXOpen.Components.Cognex.Vision.v_6_0_0_0
  children: []
  name: ErrorTime
  fullName: ErrorTime
  type: Property
  source:
    remote:
      path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
      branch: 293-Festo_CMMT-AS_class_not_derived_from_AxoDrive_just_point_to_point_movements
      repo: https://github.com/ix-ax/AXOpen.git
    id: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0.AxoDataman_Config.ErrorTime
    path: .\src\components.cognex.vision\ctrl\src\AxoDataman\v_6_0_0\TypeStructuresAndEnums\AxoDataman_Config.st
    startLine: 10
  namespace: plc.AXOpen.Components.Cognex.Vision.v_6_0_0_0
  syntax:
    content: 'ErrorTime : LTIME'
    return:
      type: LTIME
references:
- uid: plc.BOOL
  name: BOOL
  nameWithType: BOOL
  fullName: BOOL
- uid: plc.LTIME
  name: LTIME
  nameWithType: LTIME
  fullName: LTIME


