NAMESPACE AXOpen.Io
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
	        // Module bni00l3_2/16_DI
	        bni00l3_2_16_DI_BALLUFF_8_Port_IO_Link_Master_Input AT %B32 : bni00l3_2_16_DI_BALLUFF_8_Port_IO_Link_Master_Input_Layout;

	        bni00l3_2_16_DI_X01_Input AT %B33 : bni00l3_2_16_DI_X01_Input_Layout;

	        bni00l3_2_16_DI_X02_Input AT %B34 : bni00l3_2_16_DI_X02_Input_Layout;

	        bni00l3_2_16_DI_X03_Input AT %B35 : bni00l3_2_16_DI_X03_Input_Layout;

	        bni00l3_2_16_DI_X04_Input AT %B38 : bni00l3_2_16_DI_X04_Input_Layout;

	        bni00l3_2_16_DI_X05_Input AT %B39 : bni00l3_2_16_DI_X05_Input_Layout;

	        bni00l3_2_16_DI_X06_Input AT %B40 : bni00l3_2_16_DI_X06_Input_Layout;

	        bni00l3_2_16_DI_X07_Input AT %B41 : bni00l3_2_16_DI_X07_Input_Layout;

	        bni00l3_2_16_DI_X08_Input AT %B42 : bni00l3_2_16_DI_X08_Input_Layout;

	        // Module et200sp/A10
	        et200sp_A10_Input AT %B36 : et200sp_A10_Input_Layout;

	        // Module et200sp/A30
	        et200sp_A30_Input AT %B0 : et200sp_A30_Input_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

