NAMESPACE AXOpen.Io
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
	        // Module bnixg35080b5r067/2xBNI00AY_on_Port_X01
	        bnixg35080b5r067_2xBNI00AY_on_Port_X01_BALLUFF_8_Port_IO_Link_Master_Input AT %B0 : bnixg35080b5r067_2xBNI00AY_on_Port_X01_BALLUFF_8_Port_IO_Link_Master_Input_Layout;

	        bnixg35080b5r067_2xBNI00AY_on_Port_X01_X01_Input AT %B1 : bnixg35080b5r067_2xBNI00AY_on_Port_X01_X01_Input_Layout;

	        // Module et200sp/A10
	        et200sp_A10_Input AT %B62 : et200sp_A10_Input_Layout;

	        // Module et200sp/A30
	        et200sp_A30_Input AT %B30 : et200sp_A30_Input_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

