NAMESPACE AXOpen.Io
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
	        // Module bni00l3/BALLUFF_Link_module
	        bni00l3_BALLUFF_Link_module_BALLUFF_8_Port_IO_Link_Master_Input AT %B0 : bni00l3_BALLUFF_Link_module_BALLUFF_8_Port_IO_Link_Master_Input_Layout;

	        bni00l3_BALLUFF_Link_module_X01_Input AT %B1 : bni00l3_BALLUFF_Link_module_X01_Input_Layout;

	        bni00l3_BALLUFF_Link_module_X02_Input AT %B4 : bni00l3_BALLUFF_Link_module_X02_Input_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

