NAMESPACE AXOpen.Io
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Outputs : STRUCT
	        bnixg35080b5r067_IDM_LinkModule_BALLUFF_8_Port_IO_Link_Master_Output AT %B0 : bnixg35080b5r067_IDM_LinkModule_BALLUFF_8_Port_IO_Link_Master_Output_Layout;

	        // Module et200sp_1/A20
	        et200sp_1_A20_Output AT %B15 : et200sp_1_A20_Output_Layout;

	        // Module et200sp_1/A21
	        et200sp_1_A21_Output AT %B13 : et200sp_1_A21_Output_Layout;

	        // Module et200sp_1/A22
	        et200sp_1_A22_Output AT %B11 : et200sp_1_A22_Output_Layout;

	        // Module et200sp_1/A23
	        et200sp_1_A23_Output AT %B9 : et200sp_1_A23_Output_Layout;

	        // Module et200sp_1/A40
	        et200sp_1_A40_Output AT %B1 : et200sp_1_A40_Output_Layout;

	        // Module et200sp/A20
	        et200sp_A20_Output AT %B49 : et200sp_A20_Output_Layout;

	        et200sp_A30_Output AT %B17 : et200sp_A30_Output_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

