### YamlMime:ManagedReference
items:
- uid: AXOpen.Core.IAxoContextEnvironment
  commentId: T:AXOpen.Core.IAxoContextEnvironment
  id: IAxoContextEnvironment
  parent: AXOpen.Core
  children: []
  langs:
  - csharp
  - vb
  name: IAxoContextEnvironment
  nameWithType: IAxoContextEnvironment
  fullName: AXOpen.Core.IAxoContextEnvironment
  type: Interface
  source:
    remote:
      path: src/core/src/AXOpen.Core/.g/Onliners/abstractions/AxoContext/IAxoContextEnvironment.g.cs
      branch: 64-_NEW-FEATURE_Add_momentary_and_toggle_task_from_tco
      repo: https://github.com/ix-ax/ix.framework.git
    id: IAxoContextEnvironment
    path: ../src/core/src/AXOpen.Core/.g/Onliners/abstractions/AxoContext/IAxoContextEnvironment.g.cs
    startLine: 9
  assemblies:
  - ix_ax_axopen_core
  namespace: AXOpen.Core
  syntax:
    content: public interface IAxoContextEnvironment
    content.vb: Public Interface IAxoContextEnvironment
references:
- uid: AXOpen.Core
  commentId: N:AXOpen.Core
  name: AXOpen.Core
  nameWithType: AXOpen.Core
  fullName: AXOpen.Core
  spec.csharp:
  - uid: AXOpen
    name: AXOpen
  - name: .
  - uid: AXOpen.Core
    name: Core
  spec.vb:
  - uid: AXOpen
    name: AXOpen
  - name: .
  - uid: AXOpen.Core
    name: Core
