### YamlMime:ManagedReference
items:
- uid: Pocos.AXOpen.Core.IAxoContextEnvironment
  commentId: T:Pocos.AXOpen.Core.IAxoContextEnvironment
  id: IAxoContextEnvironment
  parent: Pocos.AXOpen.Core
  children: []
  langs:
  - csharp
  - vb
  name: IAxoContextEnvironment
  nameWithType: IAxoContextEnvironment
  fullName: Pocos.AXOpen.Core.IAxoContextEnvironment
  type: Interface
  source:
    remote:
      path: src/core/src/AXOpen.Core/.g/POCO/abstractions/AxoContext/IAxoContextEnvironment.g.cs
      branch: 64-_NEW-FEATURE_Add_momentary_and_toggle_task_from_tco
      repo: https://github.com/ix-ax/ix.framework.git
    id: IAxoContextEnvironment
    path: ../src/core/src/AXOpen.Core/.g/POCO/abstractions/AxoContext/IAxoContextEnvironment.g.cs
    startLine: 8
  assemblies:
  - ix_ax_axopen_core
  namespace: Pocos.AXOpen.Core
  syntax:
    content: public interface IAxoContextEnvironment
    content.vb: Public Interface IAxoContextEnvironment
references:
- uid: Pocos.AXOpen.Core
  commentId: N:Pocos.AXOpen.Core
  name: Pocos.AXOpen.Core
  nameWithType: Pocos.AXOpen.Core
  fullName: Pocos.AXOpen.Core
  spec.csharp:
  - uid: Pocos
    name: Pocos
  - name: .
  - uid: Pocos.AXOpen
    name: AXOpen
  - name: .
  - uid: Pocos.AXOpen.Core
    name: Core
  spec.vb:
  - uid: Pocos
    name: Pocos
  - name: .
  - uid: Pocos.AXOpen
    name: AXOpen
  - name: .
  - uid: Pocos.AXOpen.Core
    name: Core
