NAMESPACE AXOpen.Components.Pneumatics
    TYPE
        HwIdentifiers : UINT
        (
            plc_line_HwID := UINT#32,
            plc_line_plc_line_HwID := UINT#48,
            plc_line_plc_line_Card_reader_writer_1_HwID := UINT#51,
            plc_line_plc_line_CPU_display_1_HwID := UINT#54,
            plc_line_plc_line_DP_interface_1_HwID := UINT#60,
            plc_line_plc_line_PROFINET_interface_1_HwID := UINT#64,
            plc_line_plc_line_PROFINET_interface_1_Port_1_HwID := UINT#65,
            plc_line_plc_line_PROFINET_interface_1_Port_2_HwID := UINT#66,
            plc_line_plc_line_PROFINET_interface_2_HwID := UINT#72,
            plc_line_plc_line_PROFINET_interface_2_Port_3_HwID := UINT#73,
            plc_line_plc_line_OPC_UA_1_HwID := UINT#117,
            plc_line_plc_line_Virtual_communication_interface_HwID := UINT#135,
            profinet_plc_line_HwID := UINT#256,
            aes_d_bc_pnio_aes_d_bc_pnio_PN_IO_HwID := UINT#257,
            aes_d_bc_pnio_HwID := UINT#258,
            aes_d_bc_pnio_aes_d_bc_pnio_PN_IO_Port_1_HwID := UINT#259,
            aes_d_bc_pnio_aes_d_bc_pnio_PN_IO_Port_2_HwID := UINT#260,
            aes_d_bc_pnio_Rack_HwID := UINT#261,
            aes_d_bc_pnio_aes_d_bc_pnio_HwID := UINT#262,
            aes_d_bc_pnio_Slot_16_empty_slot_HwID := UINT#263,
            aes_d_bc_pnio_Slot_15_empty_slot_HwID := UINT#264,
            aes_d_bc_pnio_Slot_14_empty_slot_HwID := UINT#265,
            aes_d_bc_pnio_Slot_13_empty_slot_HwID := UINT#266,
            aes_d_bc_pnio_Slot_12_empty_slot_HwID := UINT#267,
            aes_d_bc_pnio_Slot_11_empty_slot_HwID := UINT#268,
            aes_d_bc_pnio_Slot_10_empty_slot_HwID := UINT#269,
            aes_d_bc_pnio_Slot_9_empty_slot_HwID := UINT#270,
            aes_d_bc_pnio_Slot_8_empty_slot_HwID := UINT#271,
            aes_d_bc_pnio_Slot_7_empty_slot_HwID := UINT#272,
            aes_d_bc_pnio_Slot_6_empty_slot_HwID := UINT#273,
            aes_d_bc_pnio_Slot_5_empty_slot_HwID := UINT#274,
            aes_d_bc_pnio_Slot_4_empty_slot_HwID := UINT#275,
            aes_d_bc_pnio_Slot_3_empty_slot_HwID := UINT#276,
            aes_d_bc_pnio_Slot_2_empty_slot_HwID := UINT#277,
            aes_d_bc_pnio_Slot_1_Valve_driver_4_valves_4_HwID := UINT#278,
            aes_d_bc_pnio_aes_d_bc_pnio_AES_Modul_HwID := UINT#279,
            plc_line_Rail_0_HwID := UINT#280,
            plc_line_A1_A1_HwID := UINT#281
        );
    END_TYPE
END_NAMESPACE

