NAMESPACE AXOpen.Components.Pneumatics
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    aes_d_bc_pnio_Slot_1_Output_Layout : STRUCT
	        Signals_0_0 AT %X0.0 : BOOL;
	        Signals_0_1 AT %X0.1 : BOOL;
	        Signals_0_2 AT %X0.2 : BOOL;
	        Signals_0_3 AT %X0.3 : BOOL;
	        Signals_0_4 AT %X0.4 : BOOL;
	        Signals_0_5 AT %X0.5 : BOOL;
	        Signals_0_6 AT %X0.6 : BOOL;
	        Signals_0_7 AT %X0.7 : BOOL;
	    END_STRUCT;
	END_TYPE
END_NAMESPACE

