NAMESPACE AXOpen.Test
    TYPE
        HwIdentifiers : UINT
        (
            plc_line_HwID := UINT#32,
            plc_line_plc_line_HwID := UINT#48,
            plc_line_plc_line_Card_reader_writer_1_HwID := UINT#51,
            plc_line_plc_line_CPU_display_1_HwID := UINT#54,
            plc_line_plc_line_DP_interface_1_HwID := UINT#60,
            plc_line_plc_line_PROFINET_interface_1_HwID := UINT#64,
            plc_line_plc_line_PROFINET_interface_1_Port_1_HwID := UINT#65,
            plc_line_plc_line_PROFINET_interface_1_Port_2_HwID := UINT#66,
            plc_line_plc_line_PROFINET_interface_2_HwID := UINT#72,
            plc_line_plc_line_PROFINET_interface_2_Port_3_HwID := UINT#73,
            plc_line_plc_line_OPC_UA_1_HwID := UINT#117,
            plc_line_plc_line_Virtual_communication_interface_HwID := UINT#135,
            profinet_plc_line_HwID := UINT#256,
            rexroth_ctrlx_drive_rexroth_ctrlx_drive_XCS_interface_PF30_HwID := UINT#257,
            rexroth_ctrlx_drive_HwID := UINT#258,
            rexroth_ctrlx_drive_rexroth_ctrlx_drive_XCS_interface_PF30_Port_1_HwID := UINT#259,
            rexroth_ctrlx_drive_rexroth_ctrlx_drive_XCS_interface_PF30_Port_2_HwID := UINT#260,
            rexroth_ctrlx_drive_Rack_HwID := UINT#261,
            rexroth_ctrlx_drive_rexroth_ctrlx_drive_HwID := UINT#262,
            rexroth_ctrlx_drive_Outputs_HwID := UINT#263,
            rexroth_ctrlx_drive_Inputs_HwID := UINT#264,
            rexroth_ctrlx_drive_S_0_0386_0_0__Position_controller__Position_actual_value_HwID := UINT#265,
            rexroth_ctrlx_drive_S_0_0535_0_0__Velocity_controller__Velocity_actual_value_HwID := UINT#266,
            rexroth_ctrlx_drive_S_0_0390_0_0__Diagnostic_message__Manufacturer_status_register_HwID := UINT#267,
            rexroth_ctrlx_drive_S_0_0135_0_0__Drive_status_word__Value_HwID := UINT#268,
            rexroth_ctrlx_drive_S_0_0144_0_0__Signal_status_word__Value_HwID := UINT#269,
            rexroth_ctrlx_drive_S_0_1720_0_2__Power_supply_control__Status_word_HwID := UINT#270,
            rexroth_ctrlx_drive_S_0_0084_0_0__Torque_force_feedback_value_HwID := UINT#271,
            rexroth_ctrlx_drive_P_0_0106_0_0__STO_function__Operating_status_HwID := UINT#272,
            rexroth_ctrlx_drive_S_0_0134_0_0__Master_control_word__Value_HwID := UINT#273,
            rexroth_ctrlx_drive_S_0_0260_0_0__Positioning_profile__Acceleration_HwID := UINT#274,
            rexroth_ctrlx_drive_S_0_0282_0_0__Drive_controlled_positioning__Command_value_HwID := UINT#275,
            rexroth_ctrlx_drive_S_0_0359_0_0__Positioning_profile__Deceleration_HwID := UINT#276,
            rexroth_ctrlx_drive_S_0_0259_0_0__Positioning_profile__Profile_velocity_HwID := UINT#277,
            rexroth_ctrlx_drive_S_0_0145_0_0__Signal_control_word__Value_HwID := UINT#278,
            rexroth_ctrlx_drive_S_0_1720_0_1__Power_supply_control__Control_word_HwID := UINT#279,
            rexroth_ctrlx_drive_S_0_0092_0_0__Torque_force_limitation__Limit_value_bipolar_HwID := UINT#280,
            rexroth_ctrlx_drive_S_0_0080_0_0__Torque_force_command_value_HwID := UINT#281,
            rexroth_ctrlx_drive_S_0_0193_0_0__Positioning_jerk_HwID := UINT#282,
            rexroth_ctrlx_drive_rexroth_ctrlx_drive_ctrlX_DRIVE_XCS_HwID := UINT#283,
            plc_line_Rail_0_HwID := UINT#284
        );
    END_TYPE
END_NAMESPACE

