NAMESPACE AXOpen.Cognex.Vision.v_6_0_0_0
    // TYPE
    //     AxoByteArray255 : 
    //     STRUCT
    //         DataChanged : BOOL;
    //         Data : ARRAY [0..254] OF BYTE;
    //     END_STRUCT;
    // END_TYPE 
    CLASS PUBLIC AxoByteArray255
        VAR PUBLIC
            DataChanged : BOOL;
            Data : ARRAY [0..254] OF BYTE;           
        END_VAR
    END_CLASS
END_NAMESPACE
