<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Packable>false</Packable>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);axopen_components_zebra_vision</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);axopen_components_zebra_vision</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AXSharp.Abstractions" />
		<PackageReference Include="AXSharp.Connector" />
		<PackageReference Include="AXSharp.Connector.S71500.WebAPI" />
	</ItemGroup>

  <!-- <ItemGroup> -->
    <!-- <None Include="..\certs\plc_line\plc_line.cer" Link="certs\plc_line\plc_line.cer"> -->
      <!-- <CopyToOutputDirectory>Always</CopyToOutputDirectory> -->
    <!-- </None> -->
  <!-- </ItemGroup> -->
	<ItemGroup>
    	<Compile Include=".g\**" />
  	</ItemGroup>

	<ItemGroup>
		<Folder Include=".g\Onliners\" />
		<Folder Include=".g\Onliners\Documentation\" />
		<Folder Include=".g\Onliners\IO\" />
		<Folder Include=".g\Onliners\Sandbox\" />
		<Folder Include=".g\POCO\" />
		<Folder Include=".meta\" />
		<Content Include=".meta\**" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\core\src\AXOpen.Core\inxton_axopen_core.csproj" />
	  <ProjectReference Include="..\..\..\abstractions\src\AXOpen.Abstractions\inxton_axopen_abstractions.csproj" />
	  <ProjectReference Include="..\..\..\timers\src\AXOpen.Timers\inxton_axopen_timers.csproj" />
	  <ProjectReference Include="..\..\..\simatic1500\ctrl\ix\inxton_axopen_simatic1500.csproj" />
	  <ProjectReference Include="..\..\src\AXOpen.Components.Zebra.Vision\inxton_axopen_components_zebra_vision.csproj" />
	</ItemGroup>
</Project>