TYPE
	HwIdentifiers : WORD
	(
		PLC_LINE_Rail_0 :=	WORD#256,
		PLC_LINE :=	WORD#48,
		PLC_LINE_Card_reader_writer_1 :=	WORD#51,
		PLC_LINE_CPU_display_1 :=	WORD#54,
		PLC_LINE_OPC_UA_1 :=	WORD#117,
		PLC_LINE_PROFINET_interface_1 :=	WORD#64,
		PLC_LINE_PROFINET_interface_1_Port_1 :=	WORD#65,
		PLC_LINE_PROFINET_interface_1_Port_2 :=	WORD#66,
		PLC_LINE_PROFINET_interface_2 :=	WORD#72,
		PLC_LINE_PROFINET_interface_2_Port_1 :=	WORD#73,
		PLC_LINE_DP_interface_1 :=	WORD#60,
		PLC_LINE_PROFINET_interface_GBIT_3 :=	WORD#120,
		PLC_LINE_PROFINET_interface_GBIT_3_Port_1 :=	WORD#121,
		rf186c_Rack :=	WORD#265,
		rf186c :=	WORD#258,
		rf186c_PROFINET_IO :=	WORD#259,
		rf186c_PROFINET_IO_Port_1 :=	WORD#260,
		rf186c_PROFINET_IO_Port_2 :=	WORD#261,
		rf186c_RF18xC_General_Parameters_V1_0 :=	WORD#262,
		rf186c_CM_configuration_1_Communication :=	WORD#264,
		rf186c_Reader_1 :=	WORD#266,
		NONE:= WORD#0
	);
END_TYPE
