NAMESPACE AXOpen.Components.Desoutter.Tightening
    TYPE
        HwIdentifiers : UINT
        (
            desoutter_cvic_ii_HwID :=UINT#258,
            desoutter_cvic_ii_Input_1_byte_1_Input_1_byte_HwID :=UINT#269,
            desoutter_cvic_ii_Input_1_byte_2_Input_1_byte_HwID :=UINT#268,
            desoutter_cvic_ii_Input_1_word_1_Input_1_word_HwID :=UINT#266,
            desoutter_cvic_ii_Input_1_word_2_Input_1_word_HwID :=UINT#264,
            desoutter_cvic_ii_Input_2_word_1_Input_2_word_HwID :=UINT#267,
            desoutter_cvic_ii_Input_2_word_2_Input_2_word_HwID :=UINT#265,
            desoutter_cvic_ii_Output_1_byte_1_Output_1_byte_HwID :=UINT#263,
            desoutter_cvic_ii_Output_1_byte_2_Output_1_byte_HwID :=UINT#262,
            desoutter_cvic_ii_Rack_HwID :=UINT#260,
            desoutter_cvic_ii_desoutter_cvic_ii_HwID :=UINT#261,
            desoutter_cvic_ii_desoutter_cvic_ii_Interface_HwID :=UINT#257,
            desoutter_cvic_ii_desoutter_cvic_ii_Interface_Port_1_HwID :=UINT#259,
            desoutter_cvic_ii_desoutter_cvic_ii_RT_HwID :=UINT#270,
            plc_line_HwID :=UINT#32,
            plc_line_Rail_0_HwID :=UINT#271,
            plc_line_plc_line_HwID :=UINT#48,
            plc_line_plc_line_CPU_display_1_HwID :=UINT#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=UINT#51,
            plc_line_plc_line_DP_interface_1_HwID :=UINT#60,
            plc_line_plc_line_OPC_UA_1_HwID :=UINT#117,
            plc_line_plc_line_PROFINET_interface_1_HwID :=UINT#64,
            plc_line_plc_line_PROFINET_interface_1_Port_1_HwID :=UINT#65,
            plc_line_plc_line_PROFINET_interface_1_Port_2_HwID :=UINT#66,
            plc_line_plc_line_PROFINET_interface_2_HwID :=UINT#72,
            plc_line_plc_line_PROFINET_interface_2_Port_3_HwID :=UINT#73,
            plc_line_plc_line_Virtual_communication_interface_HwID :=UINT#135,
            profinet_plc_line_HwID :=UINT#256,
    
            NONE := UINT#0
        );
    END_TYPE
END_NAMESPACE
