NAMESPACE AXOpen.Components.Desoutter.Tightening
    TYPE
        HwIdentifiers : WORD
        (
            plc_line_HwID :=	WORD#32,
            plc_line_Rail_0_HwID :=	WORD#273,
            plc_line_plc_line_HwID :=	WORD#48,
            plc_line_plc_line_CPU_display_1_HwID :=	WORD#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=	WORD#51,
            plc_line_plc_line_DP_interface_1_HwID :=	WORD#60,
            plc_line_plc_line_OPC_UA_1_HwID :=	WORD#117,
            plc_line_plc_line_Virtual_communication_interface_HwID :=	WORD#135,
            plc_line_plc_line_profinet_x1_HwID :=	WORD#64,
            plc_line_plc_line_profinet_x1_Port_1_HwID :=	WORD#65,
            plc_line_plc_line_profinet_x1_Port_2_HwID :=	WORD#66,
            plc_line_plc_line_profinet_x2_HwID :=	WORD#72,
            plc_line_plc_line_profinet_x2_Port_3_HwID :=	WORD#73,
            profinet_plc_line_HwID :=	WORD#256,
            wp462_t1_rh_deso_HwID :=	WORD#258,
            wp462_t1_rh_deso_Input_1_byte_1_Input_1_byte_HwID :=	WORD#269,
            wp462_t1_rh_deso_Input_1_byte_2_Input_1_byte_HwID :=	WORD#268,
            wp462_t1_rh_deso_Input_1_word_1_Input_1_word_HwID :=	WORD#266,
            wp462_t1_rh_deso_Input_1_word_2_Input_1_word_HwID :=	WORD#264,
            wp462_t1_rh_deso_Input_2_word_1_Input_2_word_HwID :=	WORD#267,
            wp462_t1_rh_deso_Input_2_word_2_Input_2_word_HwID :=	WORD#265,
            wp462_t1_rh_deso_Output_1_byte_1_Output_1_byte_HwID :=	WORD#263,
            wp462_t1_rh_deso_Output_1_byte_2_Output_1_byte_HwID :=	WORD#262,
            wp462_t1_rh_deso_Rack_HwID :=	WORD#260,
            wp462_t1_rh_deso_wp462_t1_rh_deso_HwID :=	WORD#261,
            wp462_t1_rh_deso_wp462_t1_rh_deso_RT_HwID :=	WORD#270,
            wp462_t1_rh_deso_wp462_t1_rh_deso_profinet_HwID :=	WORD#257,
            wp462_t1_rh_deso_wp462_t1_rh_deso_profinet_Port_1_HwID :=	WORD#259,
    
            NONE := WORD#0
        );
    END_TYPE
END_NAMESPACE
