NAMESPACE AXOpen.Components.Desoutter.Tightening
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Input_1_byte_1_Input_Layout : STRUCT
	        Signals_0 AT %B0 : BYTE;
	    END_STRUCT;
	END_TYPE
	
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Input_1_byte_2_Input_Layout : STRUCT
	        Signals_0 AT %B0 : BYTE;
	    END_STRUCT;
	END_TYPE
	
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Input_1_word_1_Input_Layout : STRUCT
	        Signals_0 AT %B0 : WORD;
	    END_STRUCT;
	END_TYPE
	
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Input_1_word_2_Input_Layout : STRUCT
	        Signals_0 AT %B0 : WORD;
	    END_STRUCT;
	END_TYPE
	
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Input_2_word_1_Input_Layout : STRUCT
	        Signals_0 AT %B0 : DWORD;
	    END_STRUCT;
	END_TYPE
	
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Input_2_word_2_Input_Layout : STRUCT
	        Signals_0 AT %B0 : DWORD;
	    END_STRUCT;
	END_TYPE
	
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Output_1_byte_1_Output_Layout : STRUCT
	        Signals_0 AT %B0 : BYTE;
	    END_STRUCT;
	END_TYPE
	
	TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
	    desoutter_cvic_ii_Output_1_byte_2_Output_Layout : STRUCT
	        Signals_0 AT %B0 : BYTE;
	    END_STRUCT;
	END_TYPE
END_NAMESPACE

