//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXOpen.Security.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BlazorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlazorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AXOpen.Security.Blazor.Resources.BlazorResources", typeof(BlazorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Manage.
        /// </summary>
        internal static string Account_Manage {
            get {
                return ResourceManager.GetString("Account Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available roles:.
        /// </summary>
        internal static string Available_roles_ {
            get {
                return ResourceManager.GetString("Available roles:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can change password.
        /// </summary>
        internal static string Can_change_password {
            get {
                return ResourceManager.GetString("Can change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose group.
        /// </summary>
        internal static string Choose_group {
            get {
                return ResourceManager.GetString("Choose group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string Confirm_new_password {
            get {
                return ResourceManager.GetString("Confirm new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        internal static string Create_new_group {
            get {
                return ResourceManager.GetString("Create new group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        internal static string Create_new_user {
            get {
                return ResourceManager.GetString("Create new user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created!.
        /// </summary>
        internal static string Created_ {
            get {
                return ResourceManager.GetString("Created!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        internal static string Delete_group {
            get {
                return ResourceManager.GetString("Delete group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        internal static string Delete_user {
            get {
                return ResourceManager.GetString("Delete user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted!.
        /// </summary>
        internal static string Deleted_ {
            get {
                return ResourceManager.GetString("Deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete group?.
        /// </summary>
        internal static string Do_you_want_to_delete_group {
            get {
                return ResourceManager.GetString("Do you want to delete group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete user?.
        /// </summary>
        internal static string Do_you_want_to_delete_user {
            get {
                return ResourceManager.GetString("Do you want to delete user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Management.
        /// </summary>
        internal static string Group_Management {
            get {
                return ResourceManager.GetString("Group Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string Group_name {
            get {
                return ResourceManager.GetString("Group name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully created!.
        /// </summary>
        internal static string Group_successfully_created_ {
            get {
                return ResourceManager.GetString("Group successfully created!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully deleted.
        /// </summary>
        internal static string Group_successfully_deleted {
            get {
                return ResourceManager.GetString("Group successfully deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully updated!.
        /// </summary>
        internal static string Group_successfully_updated_ {
            get {
                return ResourceManager.GetString("Group successfully updated!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group was not created..
        /// </summary>
        internal static string Group_was_not_created_ {
            get {
                return ResourceManager.GetString("Group was not created.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group was not deleted..
        /// </summary>
        internal static string Group_was_not_deleted_ {
            get {
                return ResourceManager.GetString("Group was not deleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group was not updated..
        /// </summary>
        internal static string Group_was_not_updated_ {
            get {
                return ResourceManager.GetString("Group was not updated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of groups:.
        /// </summary>
        internal static string List_of_groups_ {
            get {
                return ResourceManager.GetString("List of groups:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users:.
        /// </summary>
        internal static string List_of_users_ {
            get {
                return ResourceManager.GetString("List of users:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not created!.
        /// </summary>
        internal static string Not_created_ {
            get {
                return ResourceManager.GetString("Not created!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not deleted!.
        /// </summary>
        internal static string Not_deleted_ {
            get {
                return ResourceManager.GetString("Not deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not updated!.
        /// </summary>
        internal static string Not_updated_ {
            get {
                return ResourceManager.GetString("Not updated!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string Old_password {
            get {
                return ResourceManager.GetString("Old password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string Select_all {
            get {
                return ResourceManager.GetString("Select all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected group:.
        /// </summary>
        internal static string Selected_group_ {
            get {
                return ResourceManager.GetString("Selected group:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user:.
        /// </summary>
        internal static string Selected_user_ {
            get {
                return ResourceManager.GetString("Selected user:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not authorized to access user management. Please log in as administrator..
        /// </summary>
        internal static string Sorry__you_are_not_authorized_to_access_user_management__Please_log_in_as_administrator_ {
            get {
                return ResourceManager.GetString("Sorry, you are not authorized to access user management. Please log in as adminis" +
                        "trator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not authorized to create new users. Please log in as administrator..
        /// </summary>
        internal static string Sorry__you_are_not_authorized_to_create_new_users__Please_log_in_as_administrator_ {
            get {
                return ResourceManager.GetString("Sorry, you are not authorized to create new users. Please log in as administrator" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not logged in. Please log in..
        /// </summary>
        internal static string Sorry__you_are_not_logged_in__Please_log_in_ {
            get {
                return ResourceManager.GetString("Sorry, you are not logged in. Please log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated!.
        /// </summary>
        internal static string Updated_ {
            get {
                return ResourceManager.GetString("Updated!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string User_Management {
            get {
                return ResourceManager.GetString("User Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User succesfully deleted!.
        /// </summary>
        internal static string User_succesfully_deleted_ {
            get {
                return ResourceManager.GetString("User succesfully deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User succesfully updated..
        /// </summary>
        internal static string User_succesfully_updated_ {
            get {
                return ResourceManager.GetString("User succesfully updated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created..
        /// </summary>
        internal static string User_successfully_created_ {
            get {
                return ResourceManager.GetString("User successfully created.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not created..
        /// </summary>
        internal static string User_was_not_created_ {
            get {
                return ResourceManager.GetString("User was not created.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not updated..
        /// </summary>
        internal static string User_was_not_updated_ {
            get {
                return ResourceManager.GetString("User was not updated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong group name.
        /// </summary>
        internal static string Wrong_group_name {
            get {
                return ResourceManager.GetString("Wrong group name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong name!.
        /// </summary>
        internal static string Wrong_name_ {
            get {
                return ResourceManager.GetString("Wrong name!", resourceCulture);
            }
        }
    }
}
