TYPE
	HwIdentifiers : WORD
	(
		PLC_LINE_Rail_0 :=	WORD#256,
		PLC_LINE :=	WORD#48,
		PLC_LINE_Card_reader_writer_1 :=	WORD#51,
		PLC_LINE_CPU_display_1 :=	WORD#54,
		PLC_LINE_OPC_UA_1 :=	WORD#117,
		PLC_LINE_PROFINET_interface_1 :=	WORD#64,
		PLC_LINE_PROFINET_interface_1_Port_1 :=	WORD#65,
		PLC_LINE_PROFINET_interface_1_Port_2 :=	WORD#66,
		PLC_LINE_PROFINET_interface_2 :=	WORD#72,
		PLC_LINE_PROFINET_interface_2_Port_1 :=	WORD#73,
		PLC_LINE_DP_interface_1 :=	WORD#60,
		PLC_LINE_PROFINET_interface_GBIT_3 :=	WORD#120,
		PLC_LINE_PROFINET_interface_GBIT_3_Port_1 :=	WORD#121,
		TZ535_PN_Rack :=	WORD#264,
		TZ535_PN :=	WORD#258,
		TZ535_PN_Interface :=	WORD#259,
		TZ535_PN_Interface_Port_1 :=	WORD#260,
		TZ535_PN_Interface_Port_2 :=	WORD#261,
		TZ535_PN_2D_TZ535_PN_PROFINET_IO :=	WORD#262,
		TZ535_PN_In_Out_64_byte_1 :=	WORD#265,
		NONE:= WORD#0
	);
END_TYPE
