//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXOpen.Components.Keyence.Vision.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlcStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlcStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AXOpen.Components.Keyence.Vision.Resources.PlcStringResources", typeof(PlcStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to change the program failed..
        /// </summary>
        public static string Attempt_to_change_the_program_failed_DOT_ {
            get {
                return ResourceManager.GetString("Attempt_to_change_the_program_failed_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeProgramTask timeout..
        /// </summary>
        public static string ChangeProgramTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("ChangeProgramTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearResultDataTask timeout..
        /// </summary>
        public static string ClearResultDataTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("ClearResultDataTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorStatus.ReadFailure.
        /// </summary>
        public static string ErrorStatus_DOT_ReadFailure {
            get {
                return ResourceManager.GetString("ErrorStatus_DOT_ReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorStatus.TuneFailure.
        /// </summary>
        public static string ErrorStatus_DOT_TuneFailure {
            get {
                return ResourceManager.GetString("ErrorStatus_DOT_TuneFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadTask timeout..
        /// </summary>
        public static string ReadTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("ReadTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerTask timeout..
        /// </summary>
        public static string TriggerTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("TriggerTask_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TuneTask timeout..
        /// </summary>
        public static string TuneTask_timeout_DOT_ {
            get {
                return ResourceManager.GetString("TuneTask_timeout_DOT_", resourceCulture);
            }
        }
    }
}
