NAMESPACE AXOpen.Components.Keyence.Vision
    {S7.extern=ReadWrite}
    {#ix-attr:[Container(Layout.Stack)]}
    CLASS PUBLIC Axo_IV3_DeviceResultBits_2
        VAR PUBLIC
            {#ix-set:AttributeName = "<#Master number/total status product type#>"}
            MasterNumber : UINT;                                                                // IW1352

            {#ix-set:AttributeName = "<#Tool 17#>"}
            Tool_17 : BOOL;                                                                      // IB1354.0
            {#ix-set:AttributeName = "<#Tool 18#>"}
            Tool_18 : BOOL;                                                                      // IB1354.1
            {#ix-set:AttributeName = "<#Tool 19#>"}
            Tool_19 : BOOL;                                                                      // IB1354.2
            {#ix-set:AttributeName = "<#Tool 20#>"}
            Tool_20 : BOOL;                                                                      // IB1354.3
            {#ix-set:AttributeName = "<#Tool 21#>"}
            Tool_21 : BOOL;                                                                      // IB1354.4
            {#ix-set:AttributeName = "<#Tool 22#>"}
            Tool_22 : BOOL;                                                                      // IB1354.5
            {#ix-set:AttributeName = "<#Tool 23#>"}
            Tool_23 : BOOL;                                                                      // IB1354.6
            {#ix-set:AttributeName = "<#Tool 24#>"}
            Tool_24 : BOOL;                                                                      // IB1354.7
            {#ix-set:AttributeName = "<#Tool 25#>"}
            Tool_25 : BOOL;                                                                      // IB1355.0
            {#ix-set:AttributeName = "<#Tool 26#>"}
            Tool_26 : BOOL;                                                                      // IB1355.1
            {#ix-set:AttributeName = "<#Tool 27#>"}
            Tool_27 : BOOL;                                                                      // IB1355.2
            {#ix-set:AttributeName = "<#Tool 28#>"}
            Tool_28 : BOOL;                                                                      // IB1355.3
            {#ix-set:AttributeName = "<#Tool 29#>"}
            Tool_29 : BOOL;                                                                      // IB1355.4
            {#ix-set:AttributeName = "<#Tool 30#>"}
            Tool_30 : BOOL;                                                                      // IB1355.5
            {#ix-set:AttributeName = "<#Tool 31#>"}
            Tool_31 : BOOL;                                                                      // IB1355.6
            {#ix-set:AttributeName = "<#Tool 32#>"}
            Tool_32 : BOOL;                                                                      // IB1355.7
            {#ix-set:AttributeName = "<#Tool 33#>"}
            Tool_33 : BOOL;                                                                      // IB1356.0
            {#ix-set:AttributeName = "<#Tool 34#>"}
            Tool_34 : BOOL;                                                                      // IB1356.1
            {#ix-set:AttributeName = "<#Tool 35#>"}
            Tool_35 : BOOL;                                                                      // IB1356.2
            {#ix-set:AttributeName = "<#Tool 36#>"}
            Tool_36 : BOOL;                                                                      // IB1356.3
            {#ix-set:AttributeName = "<#Tool 37#>"}
            Tool_37 : BOOL;                                                                      // IB1356.4
            {#ix-set:AttributeName = "<#Tool 38#>"}
            Tool_38 : BOOL;                                                                      // IB1356.5
            {#ix-set:AttributeName = "<#Tool 39#>"}
            Tool_39 : BOOL;                                                                      // IB1356.6
            {#ix-set:AttributeName = "<#Tool 40#>"}
            Tool_40 : BOOL;                                                                      // IB1356.7
            {#ix-set:AttributeName = "<#Tool 41#>"}
            Tool_41 : BOOL;                                                                      // IB1357.0
            {#ix-set:AttributeName = "<#Tool 42#>"}
            Tool_42 : BOOL;                                                                      // IB1357.1
            {#ix-set:AttributeName = "<#Tool 43#>"}
            Tool_43 : BOOL;                                                                      // IB1357.2
            {#ix-set:AttributeName = "<#Tool 44#>"}
            Tool_44 : BOOL;                                                                      // IB1357.3
            {#ix-set:AttributeName = "<#Tool 45#>"}
            Tool_45 : BOOL;                                                                      // IB1357.4
            {#ix-set:AttributeName = "<#Tool 46#>"}
            Tool_46 : BOOL;                                                                      // IB1357.5
            {#ix-set:AttributeName = "<#Tool 47#>"}
            Tool_47 : BOOL;                                                                      // IB1357.6
            {#ix-set:AttributeName = "<#Tool 48#>"}
            Tool_48 : BOOL;                                                                      // IB1357.7
            {#ix-set:AttributeName = "<#Tool 49#>"}
            Tool_49 : BOOL;                                                                      // IB1358.0
            {#ix-set:AttributeName = "<#Tool 50#>"}
            Tool_50 : BOOL;                                                                      // IB1358.1
            {#ix-set:AttributeName = "<#Tool 51#>"}
            Tool_51 : BOOL;                                                                      // IB1358.2
            {#ix-set:AttributeName = "<#Tool 52#>"}
            Tool_52 : BOOL;                                                                      // IB1358.3
            {#ix-set:AttributeName = "<#Tool 53#>"}
            Tool_53 : BOOL;                                                                      // IB1358.4
            {#ix-set:AttributeName = "<#Tool 54#>"}
            Tool_54 : BOOL;                                                                      // IB1358.5
            {#ix-set:AttributeName = "<#Tool 55#>"}
            Tool_55 : BOOL;                                                                      // IB1358.6
            {#ix-set:AttributeName = "<#Tool 56#>"}
            Tool_56 : BOOL;                                                                      // IB1358.7
            {#ix-set:AttributeName = "<#Tool 57#>"}
            Tool_57 : BOOL;                                                                      // IB1359.0
            {#ix-set:AttributeName = "<#Tool 58#>"}
            Tool_58 : BOOL;                                                                      // IB1359.1
            {#ix-set:AttributeName = "<#Tool 59#>"}
            Tool_59 : BOOL;                                                                      // IB1359.2
            {#ix-set:AttributeName = "<#Tool 60#>"}
            Tool_60 : BOOL;                                                                      // IB1359.3
            {#ix-set:AttributeName = "<#Tool 61#>"}
            Tool_61 : BOOL;                                                                      // IB1359.4
            {#ix-set:AttributeName = "<#Tool 62#>"}
            Tool_62 : BOOL;                                                                      // IB1359.5
            {#ix-set:AttributeName = "<#Tool 63#>"}
            Tool_63 : BOOL;                                                                      // IB1359.6
            {#ix-set:AttributeName = "<#Tool 64#>"}
            Tool_64 : BOOL;                                                                      // IB1359.7
        END_VAR 
    END_CLASS    
END_NAMESPACE