<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>   
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
	  <RootNamespace>AXOpen.Components.Festo.Drives.Blazor</RootNamespace>

	  <!--NuGet Specific part-->
	  <Description>This library is part of AXOpen framework</Description>
	  <PackageId>AXOpen.Components.Festo.Drives.Blazor</PackageId>
	  <Title>AXOpen - AXOpen.Components.Festo.Drives</Title>

	  <!-- NuGet Common part-->
	  <PackageProjectUrl>https://github.com/inxton/</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/inxton/AXOpen</RepositoryUrl>
	  <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	  <Authors>inxton</Authors>
	  <Copyright>(c) 2023  MTS spol. s r.o.  and Contributors</Copyright>
	  <PackageTags>simatix-ax, PLC, industrial automation, SCADA, HMI, Blazor</PackageTags>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <PackageIcon>icon_128_128.png</PackageIcon>
	  <RepositoryType>git</RepositoryType>
	  <IncludeSymbols>True</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageReleaseNotes>
		  Release notes are published here:
		  https://github.com/inxton/AXOpen/releases
	  </PackageReleaseNotes>
	  <PackageReadmeFile>NUGET-README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AxoCmmtAs\AxoCmmtAsView - Copy.razor.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="AxoCmmtAs\AxoCmmtAsAnimation.razor" />
    <Content Remove="AxoCmmtAs\AxoCmmtAsContent.razor" />
    <Content Remove="AxoCmmtAs\AxoCmmtAsHeader.razor" />
    <Content Remove="AxoCmmtAs\AxoCmmtAsView - Copy.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AxoCmmtAs\AxoCmmtAsAnimation.razor.css" />
  </ItemGroup>

 

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />  
	<PackageReference Include="AXSharp.Presentation.Blazor" />
    <PackageReference Include="AXSharp.Presentation.Blazor.Controls" />
    <PackageReference Include="Humanizer" />    
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
	  
  </ItemGroup>

	<ItemGroup>
		<None Include="..\..\..\..\assets\icons\icon_128_128.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\..\NUGET-README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\core\src\AXOpen.Core.Blazor\axopen_core_blazor.csproj" />
    <ProjectReference Include="..\..\..\io\src\AXOpen.Io.blazor\AXOpen.Io.blazor.csproj" />
    <ProjectReference Include="..\AXOpen.Components.Festo.Drives\inxton_axopen_components_festo_drives.csproj" />
  </ItemGroup>
</Project>
