NAMESPACE AXOpen.Components.Ur.Robotics
    {#ix-attr:[Container(Layout.Stack)]}
    {S7.extern=ReadWrite}
    CLASS PUBLIC AxoUrRoboticsT2OIntRegs_v_1_x_x
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#Int register 0#>"}
            Register_0 : DINT;
            {#ix-set:AttributeName = "<#Int register 1#>"}
            Register_1 : DINT;
            {#ix-set:AttributeName = "<#Int register 2#>"}
            Register_2 : DINT;
            {#ix-set:AttributeName = "<#Int register 3#>"}
            Register_3 : DINT;
            {#ix-set:AttributeName = "<#Int register 4#>"}
            Register_4 : DINT;
            {#ix-set:AttributeName = "<#Int register 5#>"}
            Register_5 : DINT;
            {#ix-set:AttributeName = "<#Int register 6#>"}
            Register_6 : DINT;
            {#ix-set:AttributeName = "<#Int register 7#>"}
            Register_7 : DINT;
            {#ix-set:AttributeName = "<#Int register 8#>"}
            Register_8 : DINT;
            {#ix-set:AttributeName = "<#Int register 9#>"}
            Register_9 : DINT;
            {#ix-set:AttributeName = "<#Int register 10#>"}
            Register_10 : DINT;
            {#ix-set:AttributeName = "<#Int register 11#>"}
            Register_11 : DINT;
            {#ix-set:AttributeName = "<#Int register 12#>"}
            Register_12 : DINT;
            {#ix-set:AttributeName = "<#Int register 13#>"}
            Register_13 : DINT;
            {#ix-set:AttributeName = "<#Int register 14#>"}
            Register_14 : DINT;
            {#ix-set:AttributeName = "<#Int register 15#>"}
            Register_15 : DINT;
            {#ix-set:AttributeName = "<#Int register 16#>"}
            Register_16 : DINT;
            {#ix-set:AttributeName = "<#Int register 17#>"}
            Register_17 : DINT;
            {#ix-set:AttributeName = "<#Int register 18#>"}
            Register_18 : DINT;
            {#ix-set:AttributeName = "<#Int register 19#>"}
            Register_19 : DINT;
            {#ix-set:AttributeName = "<#Int register 20#>"}
            Register_20 : DINT;
            {#ix-set:AttributeName = "<#Int register 21#>"}
            Register_21 : DINT;
            {#ix-set:AttributeName = "<#Int register 22#>"}
            Register_22 : DINT;
            {#ix-set:AttributeName = "<#Int register 23#>"}
            Register_23 : DINT;            
        END_VAR 
    END_CLASS    
END_NAMESPACE