NAMESPACE AXOpen.Components.Ur.Robotics
    {#ix-attr:[Container(Layout.Stack)]}
    {S7.extern=ReadWrite}
    CLASS PUBLIC AxoUrRobotics_O2TReg_v_1_x_x
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#Bit register 0#>"}
            Bit_0 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 1#>"}
            Bit_1 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 2#>"}
            Bit_2 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 3#>"}
            Bit_3 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 4#>"}
            Bit_4 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 5#>"}
            Bit_5 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 6#>"}
            Bit_6 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 7#>"}
            Bit_7 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 8#>"}
            Bit_8 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 9#>"}
            Bit_9 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 10#>"}
            Bit_10 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 11#>"}
            Bit_11 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 12#>"}
            Bit_12 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 13#>"}
            Bit_13 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 14#>"}
            Bit_14 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 15#>"}
            Bit_15 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 16#>"}
            Bit_16 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 17#>"}
            Bit_17 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 18#>"}
            Bit_18 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 19#>"}
            Bit_19 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 20#>"}
            Bit_20 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 21#>"}
            Bit_21 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 22#>"}
            Bit_22 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 23#>"}
            Bit_23 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 24#>"}
            Bit_24 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 25#>"}
            Bit_25 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 26#>"}
            Bit_26 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 27#>"}
            Bit_27 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 28#>"}
            Bit_28 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 29#>"}
            Bit_29 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 30#>"}
            Bit_30 : BOOL;
            {#ix-set:AttributeName = "<#Bit register 31#>"}
            Bit_31 : BOOL;
            {#ix-set:AttributeName = "<#Int register 0#>"}
            Int_0 : DINT;
            {#ix-set:AttributeName = "<#Int register 1#>"}
            Int_1 : DINT;
            {#ix-set:AttributeName = "<#Int register 2#>"}
            Int_2 : DINT;
            {#ix-set:AttributeName = "<#Int register 3#>"}
            Int_3 : DINT;
            {#ix-set:AttributeName = "<#Int register 4#>"}
            Int_4 : DINT;
            {#ix-set:AttributeName = "<#Int register 5#>"}
            Int_5 : DINT;
            {#ix-set:AttributeName = "<#Int register 6#>"}
            Int_6 : DINT;
            {#ix-set:AttributeName = "<#Int register 7#>"}
            Int_7 : DINT;
            {#ix-set:AttributeName = "<#Int register 8#>"}
            Int_8 : DINT;
            {#ix-set:AttributeName = "<#Int register 9#>"}
            Int_9 : DINT;
            {#ix-set:AttributeName = "<#Int register 10#>"}
            Int_10 : DINT;
            {#ix-set:AttributeName = "<#Int register 11#>"}
            Int_11 : DINT;
            {#ix-set:AttributeName = "<#Float register 0#>"}
            Float_0 : REAL;
            {#ix-set:AttributeName = "<#Float register 1#>"}
            Float_1 : REAL;
            {#ix-set:AttributeName = "<#Float register 2#>"}
            Float_2 : REAL;
            {#ix-set:AttributeName = "<#Float register 3#>"}
            Float_3 : REAL;
            {#ix-set:AttributeName = "<#Float register 4#>"}
            Float_4 : REAL;
            {#ix-set:AttributeName = "<#Float register 5#>"}
            Float_5 : REAL;
            {#ix-set:AttributeName = "<#Float register 6#>"}
            Float_6 : REAL;
            {#ix-set:AttributeName = "<#Float register 7#>"}
            Float_7 : REAL;
            {#ix-set:AttributeName = "<#Float register 8#>"}
            Float_8 : REAL;
            {#ix-set:AttributeName = "<#Float register 9#>"}
            Float_9 : REAL;
            {#ix-set:AttributeName = "<#Float register 10#>"}
            Float_10 : REAL;
            {#ix-set:AttributeName = "<#Float register 11#>"}
            Float_11 : REAL;
        END_VAR 
    END_CLASS    
END_NAMESPACE