NAMESPACE AXOpen.Components.Ur.Robotics
    {#ix-attr:[Container(Layout.Stack)]}
    {S7.extern=ReadWrite}
    CLASS PUBLIC AxoUrRobotics_O2TRobot_v_1_x_x
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#SSM: Speed slider fraction mask#>"}
            SSM_SpeedSliderFractionMask : BOOL;
            {#ix-set:AttributeName = "<#Speed slider fraction#>"}
            SpeedSliderFraction : REAL;
        END_VAR 
    END_CLASS    
END_NAMESPACE