NAMESPACE AXOpen.Components.Ur.Robotics
    {#ix-attr:[Container(Layout.Stack)]}
    {S7.extern=ReadWrite}
    CLASS PUBLIC AxoUrRoboticsT2OJoints_v_1_x_x
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#Joint position 0 [rad]#>"}
            JointPosition_0 : REAL;
            {#ix-set:AttributeName = "<#Joint position 1 [rad]#>"}
            JointPosition_1 : REAL;
            {#ix-set:AttributeName = "<#Joint position 2 [rad]#>"}
            JointPosition_2 : REAL;
            {#ix-set:AttributeName = "<#Joint position 3 [rad]#>"}
            JointPosition_3 : REAL;
            {#ix-set:AttributeName = "<#Joint position 4 [rad]#>"}
            JointPosition_4 : REAL;
            {#ix-set:AttributeName = "<#Joint position 5 [rad]#>"}
            JointPosition_5 : REAL;
            {#ix-set:AttributeName = "<#Joint velocity 0 [rad/s]#>"}
            JointVelocity_0 : REAL;
            {#ix-set:AttributeName = "<#Joint velocity 1 [rad/s]#>"}
            JointVelocity_1 : REAL;
            {#ix-set:AttributeName = "<#Joint velocity 2 [rad/s]#>"}
            JointVelocity_2 : REAL;
            {#ix-set:AttributeName = "<#Joint velocity 3 [rad/s]#>"}
            JointVelocity_3 : REAL;
            {#ix-set:AttributeName = "<#Joint velocity 4 [rad/s]#>"}
            JointVelocity_4 : REAL;
            {#ix-set:AttributeName = "<#Joint velocity 5 [rad/s]#>"}
            JointVelocity_5 : REAL;
            {#ix-set:AttributeName = "<#Joint current 0 [A]#>"}
            JointCurrent_0 : REAL;
            {#ix-set:AttributeName = "<#Joint current 1 [A]#>"}
            JointCurrent_1 : REAL;
            {#ix-set:AttributeName = "<#Joint current 2 [A]#>"}
            JointCurrent_2 : REAL;
            {#ix-set:AttributeName = "<#Joint current 3 [A]#>"}
            JointCurrent_3 : REAL;
            {#ix-set:AttributeName = "<#Joint current 4 [A]#>"}
            JointCurrent_4 : REAL;
            {#ix-set:AttributeName = "<#Joint current 5 [A]#>"}
            JointCurrent_5 : REAL;
            {#ix-set:AttributeName = "<#Joint temperature 0 [°C]#>"}
            JointTemperature_0 : REAL;
            {#ix-set:AttributeName = "<#Joint temperature 1 [°C]#>"}
            JointTemperature_1 : REAL;
            {#ix-set:AttributeName = "<#Joint temperature 2 [°C]#>"}
            JointTemperature_2 : REAL;
            {#ix-set:AttributeName = "<#Joint temperature 3 [°C]#>"}
            JointTemperature_3 : REAL;
            {#ix-set:AttributeName = "<#Joint temperature 4 [°C]#>"}
            JointTemperature_4 : REAL;
            {#ix-set:AttributeName = "<#Joint temperature 5 [°C]#>"}
            JointTemperature_5 : REAL;
            {#ix-set:AttributeName = "<#Joint mode 0#>"}
            JointMode_0 : USINT;
            {#ix-set:AttributeName = "<#Joint mode 1#>"}
            JointMode_1 : USINT;
            {#ix-set:AttributeName = "<#Joint mode 2#>"}
            JointMode_2 : USINT;
            {#ix-set:AttributeName = "<#Joint mode 3#>"}
            JointMode_3 : USINT;
            {#ix-set:AttributeName = "<#Joint mode 4#>"}
            JointMode_4 : USINT;
            {#ix-set:AttributeName = "<#Joint mode 5#>"}
            JointMode_5 : USINT;
        END_VAR 
    END_CLASS    
END_NAMESPACE