NAMESPACE AXOpen.Components.Rexroth.Tightening
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
	        // Module Axo_CS351/Input_2_word_1
	        Axo_CS351_Input_2_word_1_Input AT %B0 : Axo_CS351_Input_2_word_1_Input_Layout;

	        // Module Axo_CS351/Input_4_word_1
	        Axo_CS351_Input_4_word_1_Input AT %B124 : Axo_CS351_Input_4_word_1_Input_Layout;

	        // Module Axo_CS351/Input_4_word_10
	        Axo_CS351_Input_4_word_10_Input AT %B52 : Axo_CS351_Input_4_word_10_Input_Layout;

	        // Module Axo_CS351/Input_4_word_11
	        Axo_CS351_Input_4_word_11_Input AT %B44 : Axo_CS351_Input_4_word_11_Input_Layout;

	        // Module Axo_CS351/Input_4_word_12
	        Axo_CS351_Input_4_word_12_Input AT %B36 : Axo_CS351_Input_4_word_12_Input_Layout;

	        // Module Axo_CS351/Input_4_word_13
	        Axo_CS351_Input_4_word_13_Input AT %B28 : Axo_CS351_Input_4_word_13_Input_Layout;

	        // Module Axo_CS351/Input_4_word_14
	        Axo_CS351_Input_4_word_14_Input AT %B20 : Axo_CS351_Input_4_word_14_Input_Layout;

	        // Module Axo_CS351/Input_4_word_15
	        Axo_CS351_Input_4_word_15_Input AT %B12 : Axo_CS351_Input_4_word_15_Input_Layout;

	        // Module Axo_CS351/Input_4_word_16
	        Axo_CS351_Input_4_word_16_Input AT %B4 : Axo_CS351_Input_4_word_16_Input_Layout;

	        // Module Axo_CS351/Input_4_word_2
	        Axo_CS351_Input_4_word_2_Input AT %B116 : Axo_CS351_Input_4_word_2_Input_Layout;

	        // Module Axo_CS351/Input_4_word_3
	        Axo_CS351_Input_4_word_3_Input AT %B108 : Axo_CS351_Input_4_word_3_Input_Layout;

	        // Module Axo_CS351/Input_4_word_4
	        Axo_CS351_Input_4_word_4_Input AT %B100 : Axo_CS351_Input_4_word_4_Input_Layout;

	        // Module Axo_CS351/Input_4_word_5
	        Axo_CS351_Input_4_word_5_Input AT %B92 : Axo_CS351_Input_4_word_5_Input_Layout;

	        // Module Axo_CS351/Input_4_word_6
	        Axo_CS351_Input_4_word_6_Input AT %B84 : Axo_CS351_Input_4_word_6_Input_Layout;

	        // Module Axo_CS351/Input_4_word_7
	        Axo_CS351_Input_4_word_7_Input AT %B76 : Axo_CS351_Input_4_word_7_Input_Layout;

	        // Module Axo_CS351/Input_4_word_8
	        Axo_CS351_Input_4_word_8_Input AT %B68 : Axo_CS351_Input_4_word_8_Input_Layout;

	        // Module Axo_CS351/Input_4_word_9
	        Axo_CS351_Input_4_word_9_Input AT %B60 : Axo_CS351_Input_4_word_9_Input_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

