NAMESPACE AXOpen.Components.Rexroth.Tightening
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
            Axo_CS351_Input_2_word_1 AT %B0:  DWORD;
            Axo_CS351_Input_4_word_1 AT %B124:  LWORD;
            Axo_CS351_Input_4_word_10 AT %B52:  LWORD;
            Axo_CS351_Input_4_word_11 AT %B44:  LWORD;
            Axo_CS351_Input_4_word_12 AT %B36:  LWORD;
            Axo_CS351_Input_4_word_13 AT %B28:  LWORD;
            Axo_CS351_Input_4_word_14 AT %B20:  LWORD;
            Axo_CS351_Input_4_word_15 AT %B12:  LWORD;
            Axo_CS351_Input_4_word_16 AT %B4:  LWORD;
            Axo_CS351_Input_4_word_2 AT %B116:  LWORD;
            Axo_CS351_Input_4_word_3 AT %B108:  LWORD;
            Axo_CS351_Input_4_word_4 AT %B100:  LWORD;
            Axo_CS351_Input_4_word_5 AT %B92:  LWORD;
            Axo_CS351_Input_4_word_6 AT %B84:  LWORD;
            Axo_CS351_Input_4_word_7 AT %B76:  LWORD;
            Axo_CS351_Input_4_word_8 AT %B68:  LWORD;
            Axo_CS351_Input_4_word_9 AT %B60:  LWORD;
        END_STRUCT;
    END_TYPE
END_NAMESPACE
