NAMESPACE AXOpen.Components.Rexroth.Tightening
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Outputs : STRUCT
	        // Module rexroth_cs351/Output_2_word_1
	        rexroth_cs351_Output_2_word_1_Output AT %B0 : rexroth_cs351_Output_2_word_1_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_1
	        rexroth_cs351_Output_4_word_1_Output AT %B60 : rexroth_cs351_Output_4_word_1_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_2
	        rexroth_cs351_Output_4_word_2_Output AT %B52 : rexroth_cs351_Output_4_word_2_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_3
	        rexroth_cs351_Output_4_word_3_Output AT %B44 : rexroth_cs351_Output_4_word_3_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_4
	        rexroth_cs351_Output_4_word_4_Output AT %B36 : rexroth_cs351_Output_4_word_4_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_5
	        rexroth_cs351_Output_4_word_5_Output AT %B28 : rexroth_cs351_Output_4_word_5_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_6
	        rexroth_cs351_Output_4_word_6_Output AT %B20 : rexroth_cs351_Output_4_word_6_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_7
	        rexroth_cs351_Output_4_word_7_Output AT %B12 : rexroth_cs351_Output_4_word_7_Output_Layout;

	        // Module rexroth_cs351/Output_4_word_8
	        rexroth_cs351_Output_4_word_8_Output AT %B4 : rexroth_cs351_Output_4_word_8_Output_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

