NAMESPACE AXOpen.Components.Abb.Robotics
    TYPE
        HwIdentifiers : UINT
        (
            OmniCore_HwID :=UINT#258,
            OmniCore_DI_64_bytes_DI_64_bytes_HwID :=UINT#263,
            OmniCore_DO_64_bytes_DO_64_bytes_HwID :=UINT#262,
            OmniCore_OmniCore_HwID :=UINT#261,
            OmniCore_OmniCore_OmniCore_Standard_PROFINET_Device_HwID :=UINT#264,
            OmniCore_OmniCore_profinet_HwID :=UINT#257,
            OmniCore_OmniCore_profinet_Network_Port_1_HwID :=UINT#259,
            OmniCore_Rack_HwID :=UINT#260,
            RobotBasicIO_HwID :=UINT#266,
            RobotBasicIO_DI_64_bytes_DI_64_bytes_HwID :=UINT#271,
            RobotBasicIO_DO_64_bytes_DO_64_bytes_HwID :=UINT#270,
            RobotBasicIO_Rack_HwID :=UINT#268,
            RobotBasicIO_RobotBasicIO_HwID :=UINT#269,
            RobotBasicIO_RobotBasicIO_Robot_Basic_Device_HwID :=UINT#272,
            RobotBasicIO_RobotBasicIO_profinet_HwID :=UINT#265,
            RobotBasicIO_RobotBasicIO_profinet_Network_Port_HwID :=UINT#267,
            plc_line_HwID :=UINT#32,
            plc_line_Rail_0_HwID :=UINT#273,
            plc_line_plc_line_HwID :=UINT#48,
            plc_line_plc_line_CPU_display_1_HwID :=UINT#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=UINT#51,
            plc_line_plc_line_DP_interface_1_HwID :=UINT#60,
            plc_line_plc_line_OPC_UA_1_HwID :=UINT#117,
            plc_line_plc_line_Virtual_communication_interface_HwID :=UINT#135,
            plc_line_plc_line_profinet_x1_HwID :=UINT#64,
            plc_line_plc_line_profinet_x1_Port_1_HwID :=UINT#65,
            plc_line_plc_line_profinet_x1_Port_2_HwID :=UINT#66,
            plc_line_plc_line_profinet_x2_HwID :=UINT#72,
            plc_line_plc_line_profinet_x2_Port_3_HwID :=UINT#73,
            profinet_plc_line_HwID :=UINT#256,
    
            NONE := UINT#0
        );
    END_TYPE
END_NAMESPACE
