<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AXSharp.Abstractions" Version="0.24.0-preview.158" />
		<PackageReference Include="AXSharp.Connector" Version="0.24.0-preview.158" />
	</ItemGroup>

	<ItemGroup>
    	<Compile Include=".g\**" />
  	</ItemGroup>

	<ItemGroup>
		<Folder Include=".meta\" />
		<Content Include=".meta\**" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="inxton_axopen_components_rexroth_drives.csproj" />
	  <ProjectReference Include="..\..\..\simatic1500\ctrl\ix\inxton_axopen_simatic1500.csproj" />
	</ItemGroup>
</Project>