CONFIGURATION IoAddresses
    VAR_GLOBAL
        wp462_t1_rh_deso_Input_1_byte_1_InputAddress AT %IB13: BYTE;
        wp462_t1_rh_deso_Input_1_byte_2_InputAddress AT %IB12: BYTE;
        wp462_t1_rh_deso_Input_1_word_1_InputAddress AT %IW6: WORD;
        wp462_t1_rh_deso_Input_1_word_2_InputAddress AT %IW0: WORD;
        wp462_t1_rh_deso_Input_2_word_1_InputAddress AT %ID8: DWORD;
        wp462_t1_rh_deso_Input_2_word_2_InputAddress AT %ID2: DWORD;
        wp462_t1_rh_deso_Output_1_byte_1_OutputAddress AT %QB1: BYTE;
        wp462_t1_rh_deso_Output_1_byte_2_OutputAddress AT %QB0: BYTE;

    END_VAR
END_CONFIGURATION
