NAMESPACE AXOpen.Components.Cognex.Vision
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
	        // Module cognex_dataman_280/Acquisition_Status
	        cognex_dataman_280_Acquisition_Status_Input AT %B1590 : cognex_dataman_280_Acquisition_Status_Input_Layout;

	        // Module cognex_dataman_280/ResultData_128
	        cognex_dataman_280_ResultData_128_Input AT %B1453 : cognex_dataman_280_ResultData_128_Input_Layout;

	        // Module cognex_dataman_280/Results_Status
	        cognex_dataman_280_Results_Status_Input AT %B1589 : cognex_dataman_280_Results_Status_Input_Layout;

	        // Module cognex_dataman_280/Soft_Event_Control
	        cognex_dataman_280_Soft_Event_Control_Input AT %B1593 : cognex_dataman_280_Soft_Event_Control_Input_Layout;

	        // Module cognex_dataman_380/Acquisition_Status
	        cognex_dataman_380_Acquisition_Status_Input AT %B1449 : cognex_dataman_380_Acquisition_Status_Input_Layout;

	        // Module cognex_dataman_380/ResultData_128
	        cognex_dataman_380_ResultData_128_Input AT %B1312 : cognex_dataman_380_ResultData_128_Input_Layout;

	        // Module cognex_dataman_380/Results_Status
	        cognex_dataman_380_Results_Status_Input AT %B1448 : cognex_dataman_380_Results_Status_Input_Layout;

	        // Module cognex_dataman_380/Soft_Event_Control
	        cognex_dataman_380_Soft_Event_Control_Input AT %B1452 : cognex_dataman_380_Soft_Event_Control_Input_Layout;

	        // Module cognex_insight_2800/Acquisition_Status
	        cognex_insight_2800_Acquisition_Status_Input AT %B2432 : cognex_insight_2800_Acquisition_Status_Input_Layout;

	        // Module cognex_insight_2800/Command_Control
	        cognex_insight_2800_Command_Control_Input AT %B2440 : cognex_insight_2800_Command_Control_Input_Layout;

	        // Module cognex_insight_2800/Inspection_Status
	        cognex_insight_2800_Inspection_Status_Input AT %B2436 : cognex_insight_2800_Inspection_Status_Input_Layout;

	        // Module cognex_insight_2800/ResultData_250
	        cognex_insight_2800_ResultData_250_Input AT %B2178 : cognex_insight_2800_ResultData_250_Input_Layout;

	        // Module cognex_insight_2800/ResultDataAdd_128
	        cognex_insight_2800_ResultDataAdd_128_Input AT %B1800 : cognex_insight_2800_ResultDataAdd_128_Input_Layout;

	        // Module cognex_insight_2800/ResultDataAdd_250
	        cognex_insight_2800_ResultDataAdd_250_Input AT %B1928 : cognex_insight_2800_ResultDataAdd_250_Input_Layout;

	        // Module cognex_insight_2800/ResultDataAdd_64
	        cognex_insight_2800_ResultDataAdd_64_Input AT %B1736 : cognex_insight_2800_ResultDataAdd_64_Input_Layout;

	        // Module cognex_insight_2800/SoftEvent_Control
	        cognex_insight_2800_SoftEvent_Control_Input AT %B2444 : cognex_insight_2800_SoftEvent_Control_Input_Layout;

	        // Module cognex_insight_7600/Acquisition_Status
	        cognex_insight_7600_Acquisition_Status_Input AT %B1730 : cognex_insight_7600_Acquisition_Status_Input_Layout;

	        // Module cognex_insight_7600/Command_Control
	        cognex_insight_7600_Command_Control_Input AT %B1733 : cognex_insight_7600_Command_Control_Input_Layout;

	        // Module cognex_insight_7600/Inspection_Status
	        cognex_insight_7600_Inspection_Status_Input AT %B1726 : cognex_insight_7600_Inspection_Status_Input_Layout;

	        // Module cognex_insight_7600/ResultData_128
	        cognex_insight_7600_ResultData_128_Input AT %B1594 : cognex_insight_7600_ResultData_128_Input_Layout;

	        // Module cognex_insight_7600/SoftEvent_Control
	        cognex_insight_7600_SoftEvent_Control_Input AT %B1735 : cognex_insight_7600_SoftEvent_Control_Input_Layout;

	        // Module vision_pro/Engine_Control_1
	        vision_pro_Engine_Control_1_Input AT %B1288 : vision_pro_Engine_Control_1_Input_Layout;

	        // Module vision_pro/Engine_Control_2
	        vision_pro_Engine_Control_2_Input AT %B1280 : vision_pro_Engine_Control_2_Input_Layout;

	        // Module vision_pro/Engine_Control_3
	        vision_pro_Engine_Control_3_Input AT %B1272 : vision_pro_Engine_Control_3_Input_Layout;

	        // Module vision_pro/Engine_Control_4
	        vision_pro_Engine_Control_4_Input AT %B1264 : vision_pro_Engine_Control_4_Input_Layout;

	        // Module vision_pro/Result_Data_240_bytes_1
	        vision_pro_Result_Data_240_bytes_1_Input AT %B1024 : vision_pro_Result_Data_240_bytes_1_Input_Layout;

	        // Module vision_pro/Result_Data_240_bytes_2
	        vision_pro_Result_Data_240_bytes_2_Input AT %B784 : vision_pro_Result_Data_240_bytes_2_Input_Layout;

	        // Module vision_pro/Result_Data_240_bytes_3
	        vision_pro_Result_Data_240_bytes_3_Input AT %B544 : vision_pro_Result_Data_240_bytes_3_Input_Layout;

	        // Module vision_pro/Result_Data_240_bytes_4
	        vision_pro_Result_Data_240_bytes_4_Input AT %B304 : vision_pro_Result_Data_240_bytes_4_Input_Layout;

	        // Module vision_pro/Result_Data_240_bytes_5
	        vision_pro_Result_Data_240_bytes_5_Input AT %B64 : vision_pro_Result_Data_240_bytes_5_Input_Layout;

	        // Module vision_pro/Result_Data_64_bytes_1
	        vision_pro_Result_Data_64_bytes_1_Input AT %B0 : vision_pro_Result_Data_64_bytes_1_Input_Layout;

	        // Module vision_pro/System_Control
	        vision_pro_System_Control_Input AT %B1296 : vision_pro_System_Control_Input_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

