NAMESPACE AXOpen.Components.Rexroth.Drives
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
            AxoCtrlxDriveXsc_Inputs_Submodule_1 AT %B12:  WORD;
            AxoCtrlxDriveXsc_Inputs_Submodule_2 AT %B20:  WORD;
            AxoCtrlxDriveXsc_Inputs_Submodule_3 AT %B18:  WORD;
            AxoCtrlxDriveXsc_Inputs_Submodule_4 AT %B14:  WORD;
            AxoCtrlxDriveXsc_Inputs_Submodule_5 AT %B0:  DWORD;
            AxoCtrlxDriveXsc_Inputs_Submodule_6 AT %B8:  DWORD;
            AxoCtrlxDriveXsc_Inputs_Submodule_7 AT %B4:  DWORD;
            AxoCtrlxDriveXsc_Inputs_Submodule_8 AT %B16:  WORD;
            ST3_indradrive_Input_9_Words_0 AT %B22:  WORD;
            ST3_indradrive_Input_9_Words_1 AT %B24:  WORD;
            ST3_indradrive_Input_9_Words_2 AT %B26:  WORD;
            ST3_indradrive_Input_9_Words_3 AT %B28:  WORD;
            ST3_indradrive_Input_9_Words_4 AT %B30:  WORD;
            ST3_indradrive_Input_9_Words_5 AT %B32:  WORD;
            ST3_indradrive_Input_9_Words_6 AT %B34:  WORD;
            ST3_indradrive_Input_9_Words_7 AT %B36:  WORD;
            ST3_indradrive_Input_9_Words_8 AT %B38:  WORD;
            ST3_indradrive_ParamCh_5Words_0 AT %B40:  WORD;
            ST3_indradrive_ParamCh_5Words_1 AT %B42:  WORD;
            ST3_indradrive_ParamCh_5Words_2 AT %B44:  WORD;
            ST3_indradrive_ParamCh_5Words_3 AT %B46:  WORD;
            ST3_indradrive_ParamCh_5Words_4 AT %B48:  WORD;
        END_STRUCT;
    END_TYPE
END_NAMESPACE
