NAMESPACE AXOpen.Components.Rexroth.Drives
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Outputs : STRUCT
            ST3_indradrive_Output_13_Words_0 AT %B0:  WORD;
            ST3_indradrive_Output_13_Words_1 AT %B2:  WORD;
            ST3_indradrive_Output_13_Words_2 AT %B4:  WORD;
            ST3_indradrive_Output_13_Words_3 AT %B6:  WORD;
            ST3_indradrive_Output_13_Words_4 AT %B8:  WORD;
            ST3_indradrive_Output_13_Words_5 AT %B10:  WORD;
            ST3_indradrive_Output_13_Words_6 AT %B12:  WORD;
            ST3_indradrive_Output_13_Words_7 AT %B14:  WORD;
            ST3_indradrive_Output_13_Words_8 AT %B16:  WORD;
            ST3_indradrive_Output_13_Words_9 AT %B18:  WORD;
            ST3_indradrive_Output_13_Words_10 AT %B20:  WORD;
            ST3_indradrive_Output_13_Words_11 AT %B22:  WORD;
            ST3_indradrive_Output_13_Words_12 AT %B24:  WORD;
            ST3_indradrive_ParamCh_5Words_0 AT %B26:  WORD;
            ST3_indradrive_ParamCh_5Words_1 AT %B28:  WORD;
            ST3_indradrive_ParamCh_5Words_2 AT %B30:  WORD;
            ST3_indradrive_ParamCh_5Words_3 AT %B32:  WORD;
            ST3_indradrive_ParamCh_5Words_4 AT %B34:  WORD;
        END_STRUCT;
    END_TYPE
END_NAMESPACE
