NAMESPACE AXOpen.Components.Rexroth.Drives
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Outputs : STRUCT
            AxoCtrlxDriveXsc_Outputs_Submodule_1 AT %B0:  WORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_2 AT %B24:  WORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_3 AT %B22:  WORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_4 AT %B18:  WORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_5 AT %B26:  DWORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_6 AT %B14:  DWORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_7 AT %B2:  DWORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_8 AT %B6:  DWORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_9 AT %B10:  DWORD;
            AxoCtrlxDriveXsc_Outputs_Submodule_10 AT %B20:  WORD;
            ST3_indradrive_Output_13_Words_0 AT %B30:  WORD;
            ST3_indradrive_Output_13_Words_1 AT %B32:  WORD;
            ST3_indradrive_Output_13_Words_2 AT %B34:  WORD;
            ST3_indradrive_Output_13_Words_3 AT %B36:  WORD;
            ST3_indradrive_Output_13_Words_4 AT %B38:  WORD;
            ST3_indradrive_Output_13_Words_5 AT %B40:  WORD;
            ST3_indradrive_Output_13_Words_6 AT %B42:  WORD;
            ST3_indradrive_Output_13_Words_7 AT %B44:  WORD;
            ST3_indradrive_Output_13_Words_8 AT %B46:  WORD;
            ST3_indradrive_Output_13_Words_9 AT %B48:  WORD;
            ST3_indradrive_Output_13_Words_10 AT %B50:  WORD;
            ST3_indradrive_Output_13_Words_11 AT %B52:  WORD;
            ST3_indradrive_Output_13_Words_12 AT %B54:  WORD;
            ST3_indradrive_ParamCh_5Words_0 AT %B56:  WORD;
            ST3_indradrive_ParamCh_5Words_1 AT %B58:  WORD;
            ST3_indradrive_ParamCh_5Words_2 AT %B60:  WORD;
            ST3_indradrive_ParamCh_5Words_3 AT %B62:  WORD;
            ST3_indradrive_ParamCh_5Words_4 AT %B64:  WORD;
        END_STRUCT;
    END_TYPE
END_NAMESPACE
