CONFIGURATION IoAddresses
    VAR_GLOBAL
        rf186c_cyc_CM_InputAddress AT %IW308: WORD;
        rf186c_cyc_CM_OutputAddress AT %QW292: WORD;
        rf186c_cyc_RF260R_1_InputAddress_0 AT %IL276: LWORD;
        rf186c_cyc_RF260R_1_InputAddress_1 AT %IL284: LWORD;
        rf186c_cyc_RF260R_1_InputAddress_2 AT %IL292: LWORD;
        rf186c_cyc_RF260R_1_InputAddress_3 AT %IL300: LWORD;
        rf186c_cyc_RF260R_1_OutputAddress_0 AT %QL260: LWORD;
        rf186c_cyc_RF260R_1_OutputAddress_1 AT %QL268: LWORD;
        rf186c_cyc_RF260R_1_OutputAddress_2 AT %QL276: LWORD;
        rf186c_cyc_RF260R_1_OutputAddress_3 AT %QL284: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_0 AT %IL148: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_1 AT %IL156: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_2 AT %IL164: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_3 AT %IL172: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_4 AT %IL180: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_5 AT %IL188: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_6 AT %IL196: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_7 AT %IL204: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_8 AT %IL212: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_9 AT %IL220: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_10 AT %IL228: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_11 AT %IL236: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_12 AT %IL244: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_13 AT %IL252: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_14 AT %IL260: LWORD;
        rf186c_cyc_RF340R_1_InputAddress_15 AT %IL268: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_0 AT %QL132: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_1 AT %QL140: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_2 AT %QL148: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_3 AT %QL156: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_4 AT %QL164: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_5 AT %QL172: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_6 AT %QL180: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_7 AT %QL188: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_8 AT %QL196: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_9 AT %QL204: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_10 AT %QL212: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_11 AT %QL220: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_12 AT %QL228: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_13 AT %QL236: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_14 AT %QL244: LWORD;
        rf186c_cyc_RF340R_1_OutputAddress_15 AT %QL252: LWORD;

    END_VAR
END_CONFIGURATION
