NAMESPACE AXOpen.Components.Siem.Identification
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Inputs : STRUCT
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_0 AT %B0:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_1 AT %B8:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_2 AT %B16:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_3 AT %B24:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_4 AT %B32:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_5 AT %B40:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_6 AT %B48:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_7 AT %B56:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_8 AT %B64:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_9 AT %B72:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_10 AT %B80:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_11 AT %B88:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_12 AT %B96:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_13 AT %B104:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_14 AT %B112:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_15 AT %B120:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_16 AT %B128:  LWORD;
            et200sp_CM_4xIO_Link_RF200_CM_4xIO_Link_V2_2_144I_128O_1_17 AT %B136:  LWORD;
            rf186c_CM_1 AT %B146:  WORD;
            rf186c_Reader_1 AT %B144:  WORD;
            rf186c_cyc_CM AT %B308:  WORD;
            rf186c_cyc_RF260R_1_0 AT %B276:  LWORD;
            rf186c_cyc_RF260R_1_1 AT %B284:  LWORD;
            rf186c_cyc_RF260R_1_2 AT %B292:  LWORD;
            rf186c_cyc_RF260R_1_3 AT %B300:  LWORD;
            rf186c_cyc_RF340R_1_0 AT %B148:  LWORD;
            rf186c_cyc_RF340R_1_1 AT %B156:  LWORD;
            rf186c_cyc_RF340R_1_2 AT %B164:  LWORD;
            rf186c_cyc_RF340R_1_3 AT %B172:  LWORD;
            rf186c_cyc_RF340R_1_4 AT %B180:  LWORD;
            rf186c_cyc_RF340R_1_5 AT %B188:  LWORD;
            rf186c_cyc_RF340R_1_6 AT %B196:  LWORD;
            rf186c_cyc_RF340R_1_7 AT %B204:  LWORD;
            rf186c_cyc_RF340R_1_8 AT %B212:  LWORD;
            rf186c_cyc_RF340R_1_9 AT %B220:  LWORD;
            rf186c_cyc_RF340R_1_10 AT %B228:  LWORD;
            rf186c_cyc_RF340R_1_11 AT %B236:  LWORD;
            rf186c_cyc_RF340R_1_12 AT %B244:  LWORD;
            rf186c_cyc_RF340R_1_13 AT %B252:  LWORD;
            rf186c_cyc_RF340R_1_14 AT %B260:  LWORD;
            rf186c_cyc_RF340R_1_15 AT %B268:  LWORD;
        END_STRUCT;
    END_TYPE
END_NAMESPACE
