NAMESPACE AXOpen.Core
    CLASS PUBLIC AxoDialogBase EXTENDS AxoRemoteTask



        // METHOD PUBLIC ABSTRACT FB_init : BOOL
        //     VAR_INPUT
        //         bInitRetains : BOOL;
        //         bInCopyCode : BOOL;
        //         ParentObject : IAxoObject;
        //     END_VAR
        // END_METHOD
        /*METHOD PUBLIC ABSTRACT OnStart
            
        END_METHOD*/
        
    END_CLASS
END_NAMESPACE