<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>    
    <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="CliWrap" />
	  <PackageReference Include="CommandLineParser" />
	  <PackageReference Include="Octokit" />
	  <PackageReference Include="Octokit.Extensions" />
	  <PackageReference Include="Cake.Frosting" />
	  <PackageReference Include="Cake.Powershell" />
	  <PackageReference Include="Polly" />  
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="FilteredSolution\" />
  </ItemGroup>
</Project>