<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AXSharp.Abstractions" />
		<PackageReference Include="AXSharp.Connector" />
	</ItemGroup>

	<ItemGroup>
    	<Compile Include=".g\**" />
  	</ItemGroup>

	<ItemGroup>
		<Folder Include=".meta\" />
		<Content Include=".meta\**" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\abstractions\app\ix\abstractions_app.csproj" />
	  <ProjectReference Include="..\..\..\abstractions\src\AXOpen.Abstractions\inxton_axopen_abstractions.csproj" />
	  <ProjectReference Include="..\..\..\components.abb.robotics\app\ix\app_axopen_components_abb_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.abb.robotics\src\AXOpen.Components.Abb.Robotics\inxton_axopen_components_abb_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.abstractions\app\ix\components_abstractions_app.csproj" />
	  <ProjectReference Include="..\..\..\components.abstractions\src\AXOpen.Components.Abstractions\inxton_axopen_components_abstractions.csproj" />
	  <ProjectReference Include="..\..\..\components.balluff.identification\app\ix\app_axopen_components_balluff_identification.csproj" />
	  <ProjectReference Include="..\..\..\components.balluff.identification\src\AXOpen.Components.Balluff.Identification\inxton_axopen_components_balluff_identification.csproj" />
	  <ProjectReference Include="..\..\..\components.cognex.vision\app\ix\app_axopen_components_cognex_vision.csproj" />
	  <ProjectReference Include="..\..\..\components.cognex.vision\src\AXOpen.Components.Cognex.Vision\inxton_axopen_components_cognex_vision.csproj" />
	  <ProjectReference Include="..\..\..\components.desoutter.tightening\app\ix\app_axopen_components_desoutter_tightening.csproj" />
	  <ProjectReference Include="..\..\..\components.desoutter.tightening\src\AXOpen.Components.Desoutter.Tightening\inxton_axopen_components_desoutter_tightening.csproj" />
	  <ProjectReference Include="..\..\..\components.drives\app\ix\app_axopen_components_drives.csproj" />
	  <ProjectReference Include="..\..\..\components.drives\src\AXOpen.Components.Drives\inxton_axopen_components_drives.csproj" />
	  <ProjectReference Include="..\..\..\components.elements\app\ix\elementscomponents.csproj" />
	  <ProjectReference Include="..\..\..\components.elements\src\AXOpen.Components.Elements\inxton_axopen_components_elements.csproj" />
	  <ProjectReference Include="..\..\..\components.festo.drives\app\ix\app_axopen_components_festo_drives.csproj" />
	  <ProjectReference Include="..\..\..\components.festo.drives\src\AXOpen.Components.Festo.Drives\inxton_axopen_components_festo_drives.csproj" />
	  <ProjectReference Include="..\..\..\components.kuka.robotics\app\ix\app_axopen_components_kuka_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.kuka.robotics\src\AXOpen.Components.Kuka.Robotics\inxton_axopen_components_kuka_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.mitsubishi.robotics\app\ix\app_axopen_components_mitsubishi_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.mitsubishi.robotics\src\AXOpen.Components.Mitsubishi.Robotics\inxton_axopen_components_mitsubishi_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.pneumatics\app\ix\pneumaticcomponents.csproj" />
	  <ProjectReference Include="..\..\..\components.pneumatics\src\AXOpen.Components.Pneumatics\inxton_axopen_components_pneumatics.csproj" />
	  <ProjectReference Include="..\..\..\components.rexroth.drives\app\ix\app_axopen_components_rexroth_drives.csproj" />
	  <ProjectReference Include="..\..\..\components.rexroth.drives\src\AXOpen.Components.Rexroth.Drives\inxton_axopen_components_rexroth_drives.csproj" />
	  <ProjectReference Include="..\..\..\components.rexroth.press\app\ix\app_axopen_components_rexroth_press.csproj" />
	  <ProjectReference Include="..\..\..\components.rexroth.press\src\AXOpen.Components.Rexroth.Press\inxton_axopen_components_rexroth_press.csproj" />
	  <ProjectReference Include="..\..\..\components.robotics\app\ix\app_axopen_components_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.robotics\src\AXOpen.Components.Robotics\inxton_axopen_components_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.siem.identification\app\ix\app_axopen_components_siem_identification.csproj" />
	  <ProjectReference Include="..\..\..\components.siem.identification\src\AXOpen.Components.Siem.Identification\inxton_axopen_components_siem_identification.csproj" />
	  <ProjectReference Include="..\..\..\components.ur.robotics\app\ix\app_axopen_components_ur_robotics.csproj" />
	  <ProjectReference Include="..\..\..\components.ur.robotics\src\AXOpen.Components.Ur.Robotics\inxton_axopen_components_ur_robotics.csproj" />
	  <ProjectReference Include="..\..\..\core\app\ix\ix_axopencore.csproj" />
	  <ProjectReference Include="..\..\..\core\src\AXOpen.Core\inxton_axopen_core.csproj" />
	  <ProjectReference Include="..\..\..\data\app\ix\axopen_data_app.csproj" />
	  <ProjectReference Include="..\..\..\data\src\AXOpen.Data\inxton_axopen_data.csproj" />
	  <ProjectReference Include="..\..\..\inspectors\app\ix\axopen_inspectors.csproj" />
	  <ProjectReference Include="..\..\..\inspectors\src\AXOpen.Inspectors\inxton_axopen_inspectors.csproj" />
	  <ProjectReference Include="..\..\..\integrations\src\AXOpen.Integrations\axopen_integrations.csproj" />
	  <ProjectReference Include="..\..\..\io\app\ix\app_axopen_io.csproj" />
	  <ProjectReference Include="..\..\..\io\src\AXOpen.Io\inxton_axopen_io.csproj" />
	  <ProjectReference Include="..\..\..\probers\app\ix\probers_app.csproj" />
	  <ProjectReference Include="..\..\..\probers\src\AXOpen.Probers\inxton_axopen_probers.csproj" />
	  <ProjectReference Include="..\..\..\simatic1500\app\ix\simatic1500_app.csproj" />
	  <ProjectReference Include="..\..\..\simatic1500\ctrl\ix\inxton_axopen_simatic1500.csproj" />
	  <ProjectReference Include="..\..\..\template.axolibrary\app\ix\app_apaxappname.csproj" />
	  <ProjectReference Include="..\..\..\template.axolibrary\src\projname\inxton_apaxlibname.csproj" />
	  <ProjectReference Include="..\..\..\timers\app\ix\timers_app.csproj" />
	  <ProjectReference Include="..\..\..\timers\src\AXOpen.Timers\inxton_axopen_timers.csproj" />
	  <ProjectReference Include="..\..\..\utils\app\ix\utils_app.csproj" />
	  <ProjectReference Include="..\..\..\utils\src\AXOpen.Utils\inxton_axopen_utils.csproj" />
	  <ProjectReference Include="..\..\..\data\tests\AXOpen.Repository.Integration.Tests_L4\ix\axopen_integration_tests_l4.csproj" />
	  <ProjectReference Include="..\..\..\components.keyence.vision\app\ix\app_axopen_components_keyence_vision.csproj" />
	  <ProjectReference Include="..\..\..\components.keyence.vision\src\AXOpen.Components.Keyence.Vision\inxton_axopen_components_keyence_vision.csproj" />
	  <ProjectReference Include="..\..\..\components.rexroth.tightening\app\ix\app_axopen_components_rexroth_tightening.csproj" />
	  <ProjectReference Include="..\..\..\components.rexroth.tightening\src\AXOpen.Components.Rexroth.Tightening\inxton_axopen_components_rexroth_tightening.csproj" />
	  <ProjectReference Include="..\..\..\data\tests\AXOpen.Data.Tests_L1\ix\axopen_data_tests_l1.csproj" />
	  <ProjectReference Include="..\..\..\components.dukane.welders\app\ix\app_axopen_components_dukane_welders.csproj" />
	  <ProjectReference Include="..\..\..\components.dukane.welders\src\AXOpen.Components.Dukane.Welders\inxton_axopen_components_dukane_welders.csproj" />
	</ItemGroup>
	
</Project>