NAMESPACE AXOpen.Components.Dukane.Welders
    {S7.extern=ReadWrite}
    {#ix-attr:[Container(Layout.Wrap)]}
    CLASS PUBLIC Axo_IQ_SeriesWelder_HMI
        VAR PUBLIC 
            {#ix-set:AttributeName = "<#c#>"}
            c : Axo_IQ_SeriesWelder_HMI_command;
            {#ix-set:AttributeName = "<#s#>"}
            s : Axo_IQ_SeriesWelder_HMI_status;
            {#ix-set:AttributeName = "<#e#>"}
            e : Axo_IQ_SeriesWelder_HMI_errors;
        END_VAR 
    END_CLASS   
END_NAMESPACE
