//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXOpen.Components.Rexroth.Drives.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlcStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlcStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AXOpen.Components.Rexroth.Drives.Resources.PlcStringResources", typeof(PlcStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoHalt_Task timeout..
        /// </summary>
        public static string AxoHalt_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoHalt_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoHome_Task timeout..
        /// </summary>
        public static string AxoHome_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoHome_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoMoveAbsolute_Task timeout..
        /// </summary>
        public static string AxoMoveAbsolute_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoMoveAbsolute_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoMoveAdditive_Task timeout..
        /// </summary>
        public static string AxoMoveAdditive_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoMoveAdditive_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoMoveRelative_Task timeout..
        /// </summary>
        public static string AxoMoveRelative_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoMoveRelative_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoMoveVelocity_Task timeout..
        /// </summary>
        public static string AxoMoveVelocity_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoMoveVelocity_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoSetPosition_Task timeout..
        /// </summary>
        public static string AxoSetPosition_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoSetPosition_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxoStop_Task timeout..
        /// </summary>
        public static string AxoStop_UNDERSCORE_Task_timeout_DOT_ {
            get {
                return ResourceManager.GetString("AxoStop_UNDERSCORE_Task_timeout_DOT_", resourceCulture);
            }
        }
    }
}
