TYPE
    HwIdentifiers : WORD
    (
        PROFINET_IO_System_HwID :=	WORD#256,
        ST3_indradrive_HwID :=	WORD#260,
        ST3_indradrive_F_Modul_not_used_ID_FMod_NotUsed_HwID :=	WORD#266,
        ST3_indradrive_Input_9_Words_ID_InMod_9Words_HwID :=	WORD#264,
        ST3_indradrive_Output_13_Words_ID_OutMod_13Words_HwID :=	WORD#263,
        ST3_indradrive_ParamCh_IDN_ID_PaCh_5Words_HwID :=	WORD#265,
        ST3_indradrive_Rack_HwID :=	WORD#261,
        ST3_indradrive_ST3_indradrive_HwID :=	WORD#262,
        ST3_indradrive_ST3_indradrive_DAP_1_HwID :=	WORD#267,
        ST3_indradrive_ST3_indradrive_profinet_HwID :=	WORD#257,
        ST3_indradrive_ST3_indradrive_profinet_Port_1___RJ45_HwID :=	WORD#258,
        ST3_indradrive_ST3_indradrive_profinet_Port_2___RJ45_HwID :=	WORD#259,
        plc_line_HwID :=	WORD#32,
        plc_line_Rail_0_HwID :=	WORD#268,
        plc_line_plc_line_HwID :=	WORD#48,
        plc_line_plc_line__plc_line_HwID :=	WORD#49,
        plc_line_plc_line_CPU_display_1_HwID :=	WORD#54,
        plc_line_plc_line_CPU_exec_unit_1_HwID :=	WORD#52,
        plc_line_plc_line_Card_reader_writer_1_HwID :=	WORD#51,
        plc_line_plc_line_DP_interface_1_HwID :=	WORD#60,
        plc_line_plc_line_LicenseManager_1_HwID :=	WORD#42,
        plc_line_plc_line_OPC_UA_1_HwID :=	WORD#117,
        plc_line_plc_line_PROFINET_interface_2_HwID :=	WORD#72,
        plc_line_plc_line_PROFINET_interface_2_Port_1_HwID :=	WORD#73,
        plc_line_plc_line_Virtual_communication_interface_HwID :=	WORD#135,
        plc_line_plc_line_plc_line_HwID :=	WORD#50,
        plc_line_plc_line_profinet_x1_HwID :=	WORD#64,
        plc_line_plc_line_profinet_x1_Port1_HwID :=	WORD#65,
        plc_line_plc_line_profinet_x1_Port2_HwID :=	WORD#66,

        NONE := WORD#0
    );
END_TYPE
