CONFIGURATION IoAddresses
    VAR_GLOBAL

        // Module keyence_iv3/CommandControl
        keyence_iv3_CommandControl_Output AT %QB135 : keyence_iv3_CommandControl_Output_Layout;

        // Module keyence_iv3/CommandStatusBits
        keyence_iv3_CommandStatusBits_Input AT %IB1526 : keyence_iv3_CommandStatusBits_Input_Layout;

        // Module keyence_iv3/DeviceResultBits_1
        keyence_iv3_DeviceResultBits_1_Input AT %IB1522 : keyence_iv3_DeviceResultBits_1_Input_Layout;

        // Module keyence_iv3/DeviceResultBits_2
        keyence_iv3_DeviceResultBits_2_Input AT %IB170 : keyence_iv3_DeviceResultBits_2_Input_Layout;

        // Module keyence_iv3/DeviceStatistics
        keyence_iv3_DeviceStatistics_Input AT %IB1478 : keyence_iv3_DeviceStatistics_Input_Layout;

        // Module keyence_iv3/DeviceStatusWords
        keyence_iv3_DeviceStatusWords_Input AT %IB1506 : keyence_iv3_DeviceStatusWords_Input_Layout;

        // Module keyence_iv3/PositionAdjustResult
        keyence_iv3_PositionAdjustResult_Input AT %IB1458 : keyence_iv3_PositionAdjustResult_Input_Layout;

        // Module keyence_iv3/ToolResult_1
        keyence_iv3_ToolResult_1_Input AT %IB1438 : keyence_iv3_ToolResult_1_Input_Layout;

        // Module keyence_iv3/ToolResult_10
        keyence_iv3_ToolResult_10_Input AT %IB1258 : keyence_iv3_ToolResult_10_Input_Layout;

        // Module keyence_iv3/ToolResult_11
        keyence_iv3_ToolResult_11_Input AT %IB1238 : keyence_iv3_ToolResult_11_Input_Layout;

        // Module keyence_iv3/ToolResult_12
        keyence_iv3_ToolResult_12_Input AT %IB1218 : keyence_iv3_ToolResult_12_Input_Layout;

        // Module keyence_iv3/ToolResult_13
        keyence_iv3_ToolResult_13_Input AT %IB1198 : keyence_iv3_ToolResult_13_Input_Layout;

        // Module keyence_iv3/ToolResult_14
        keyence_iv3_ToolResult_14_Input AT %IB1178 : keyence_iv3_ToolResult_14_Input_Layout;

        // Module keyence_iv3/ToolResult_15
        keyence_iv3_ToolResult_15_Input AT %IB1158 : keyence_iv3_ToolResult_15_Input_Layout;

        // Module keyence_iv3/ToolResult_16
        keyence_iv3_ToolResult_16_Input AT %IB1138 : keyence_iv3_ToolResult_16_Input_Layout;

        // Module keyence_iv3/ToolResult_17
        keyence_iv3_ToolResult_17_Input AT %IB1118 : keyence_iv3_ToolResult_17_Input_Layout;

        // Module keyence_iv3/ToolResult_18
        keyence_iv3_ToolResult_18_Input AT %IB1098 : keyence_iv3_ToolResult_18_Input_Layout;

        // Module keyence_iv3/ToolResult_19
        keyence_iv3_ToolResult_19_Input AT %IB1078 : keyence_iv3_ToolResult_19_Input_Layout;

        // Module keyence_iv3/ToolResult_2
        keyence_iv3_ToolResult_2_Input AT %IB1418 : keyence_iv3_ToolResult_2_Input_Layout;

        // Module keyence_iv3/ToolResult_20
        keyence_iv3_ToolResult_20_Input AT %IB1058 : keyence_iv3_ToolResult_20_Input_Layout;

        // Module keyence_iv3/ToolResult_21
        keyence_iv3_ToolResult_21_Input AT %IB1038 : keyence_iv3_ToolResult_21_Input_Layout;

        // Module keyence_iv3/ToolResult_22
        keyence_iv3_ToolResult_22_Input AT %IB1018 : keyence_iv3_ToolResult_22_Input_Layout;

        // Module keyence_iv3/ToolResult_23
        keyence_iv3_ToolResult_23_Input AT %IB998 : keyence_iv3_ToolResult_23_Input_Layout;

        // Module keyence_iv3/ToolResult_24
        keyence_iv3_ToolResult_24_Input AT %IB978 : keyence_iv3_ToolResult_24_Input_Layout;

        // Module keyence_iv3/ToolResult_25
        keyence_iv3_ToolResult_25_Input AT %IB958 : keyence_iv3_ToolResult_25_Input_Layout;

        // Module keyence_iv3/ToolResult_26
        keyence_iv3_ToolResult_26_Input AT %IB938 : keyence_iv3_ToolResult_26_Input_Layout;

        // Module keyence_iv3/ToolResult_27
        keyence_iv3_ToolResult_27_Input AT %IB918 : keyence_iv3_ToolResult_27_Input_Layout;

        // Module keyence_iv3/ToolResult_28
        keyence_iv3_ToolResult_28_Input AT %IB898 : keyence_iv3_ToolResult_28_Input_Layout;

        // Module keyence_iv3/ToolResult_29
        keyence_iv3_ToolResult_29_Input AT %IB878 : keyence_iv3_ToolResult_29_Input_Layout;

        // Module keyence_iv3/ToolResult_3
        keyence_iv3_ToolResult_3_Input AT %IB1398 : keyence_iv3_ToolResult_3_Input_Layout;

        // Module keyence_iv3/ToolResult_30
        keyence_iv3_ToolResult_30_Input AT %IB858 : keyence_iv3_ToolResult_30_Input_Layout;

        // Module keyence_iv3/ToolResult_31
        keyence_iv3_ToolResult_31_Input AT %IB838 : keyence_iv3_ToolResult_31_Input_Layout;

        // Module keyence_iv3/ToolResult_32
        keyence_iv3_ToolResult_32_Input AT %IB818 : keyence_iv3_ToolResult_32_Input_Layout;

        // Module keyence_iv3/ToolResult_33
        keyence_iv3_ToolResult_33_Input AT %IB798 : keyence_iv3_ToolResult_33_Input_Layout;

        // Module keyence_iv3/ToolResult_34
        keyence_iv3_ToolResult_34_Input AT %IB778 : keyence_iv3_ToolResult_34_Input_Layout;

        // Module keyence_iv3/ToolResult_35
        keyence_iv3_ToolResult_35_Input AT %IB758 : keyence_iv3_ToolResult_35_Input_Layout;

        // Module keyence_iv3/ToolResult_36
        keyence_iv3_ToolResult_36_Input AT %IB738 : keyence_iv3_ToolResult_36_Input_Layout;

        // Module keyence_iv3/ToolResult_37
        keyence_iv3_ToolResult_37_Input AT %IB718 : keyence_iv3_ToolResult_37_Input_Layout;

        // Module keyence_iv3/ToolResult_38
        keyence_iv3_ToolResult_38_Input AT %IB698 : keyence_iv3_ToolResult_38_Input_Layout;

        // Module keyence_iv3/ToolResult_39
        keyence_iv3_ToolResult_39_Input AT %IB678 : keyence_iv3_ToolResult_39_Input_Layout;

        // Module keyence_iv3/ToolResult_4
        keyence_iv3_ToolResult_4_Input AT %IB1378 : keyence_iv3_ToolResult_4_Input_Layout;

        // Module keyence_iv3/ToolResult_40
        keyence_iv3_ToolResult_40_Input AT %IB658 : keyence_iv3_ToolResult_40_Input_Layout;

        // Module keyence_iv3/ToolResult_41
        keyence_iv3_ToolResult_41_Input AT %IB638 : keyence_iv3_ToolResult_41_Input_Layout;

        // Module keyence_iv3/ToolResult_42
        keyence_iv3_ToolResult_42_Input AT %IB618 : keyence_iv3_ToolResult_42_Input_Layout;

        // Module keyence_iv3/ToolResult_43
        keyence_iv3_ToolResult_43_Input AT %IB598 : keyence_iv3_ToolResult_43_Input_Layout;

        // Module keyence_iv3/ToolResult_44
        keyence_iv3_ToolResult_44_Input AT %IB578 : keyence_iv3_ToolResult_44_Input_Layout;

        // Module keyence_iv3/ToolResult_45
        keyence_iv3_ToolResult_45_Input AT %IB558 : keyence_iv3_ToolResult_45_Input_Layout;

        // Module keyence_iv3/ToolResult_46
        keyence_iv3_ToolResult_46_Input AT %IB538 : keyence_iv3_ToolResult_46_Input_Layout;

        // Module keyence_iv3/ToolResult_47
        keyence_iv3_ToolResult_47_Input AT %IB518 : keyence_iv3_ToolResult_47_Input_Layout;

        // Module keyence_iv3/ToolResult_48
        keyence_iv3_ToolResult_48_Input AT %IB498 : keyence_iv3_ToolResult_48_Input_Layout;

        // Module keyence_iv3/ToolResult_49
        keyence_iv3_ToolResult_49_Input AT %IB478 : keyence_iv3_ToolResult_49_Input_Layout;

        // Module keyence_iv3/ToolResult_5
        keyence_iv3_ToolResult_5_Input AT %IB1358 : keyence_iv3_ToolResult_5_Input_Layout;

        // Module keyence_iv3/ToolResult_50
        keyence_iv3_ToolResult_50_Input AT %IB458 : keyence_iv3_ToolResult_50_Input_Layout;

        // Module keyence_iv3/ToolResult_51
        keyence_iv3_ToolResult_51_Input AT %IB438 : keyence_iv3_ToolResult_51_Input_Layout;

        // Module keyence_iv3/ToolResult_52
        keyence_iv3_ToolResult_52_Input AT %IB418 : keyence_iv3_ToolResult_52_Input_Layout;

        // Module keyence_iv3/ToolResult_53
        keyence_iv3_ToolResult_53_Input AT %IB398 : keyence_iv3_ToolResult_53_Input_Layout;

        // Module keyence_iv3/ToolResult_54
        keyence_iv3_ToolResult_54_Input AT %IB378 : keyence_iv3_ToolResult_54_Input_Layout;

        // Module keyence_iv3/ToolResult_55
        keyence_iv3_ToolResult_55_Input AT %IB358 : keyence_iv3_ToolResult_55_Input_Layout;

        // Module keyence_iv3/ToolResult_56
        keyence_iv3_ToolResult_56_Input AT %IB338 : keyence_iv3_ToolResult_56_Input_Layout;

        // Module keyence_iv3/ToolResult_57
        keyence_iv3_ToolResult_57_Input AT %IB318 : keyence_iv3_ToolResult_57_Input_Layout;

        // Module keyence_iv3/ToolResult_58
        keyence_iv3_ToolResult_58_Input AT %IB298 : keyence_iv3_ToolResult_58_Input_Layout;

        // Module keyence_iv3/ToolResult_59
        keyence_iv3_ToolResult_59_Input AT %IB278 : keyence_iv3_ToolResult_59_Input_Layout;

        // Module keyence_iv3/ToolResult_6
        keyence_iv3_ToolResult_6_Input AT %IB1338 : keyence_iv3_ToolResult_6_Input_Layout;

        // Module keyence_iv3/ToolResult_60
        keyence_iv3_ToolResult_60_Input AT %IB258 : keyence_iv3_ToolResult_60_Input_Layout;

        // Module keyence_iv3/ToolResult_61
        keyence_iv3_ToolResult_61_Input AT %IB238 : keyence_iv3_ToolResult_61_Input_Layout;

        // Module keyence_iv3/ToolResult_62
        keyence_iv3_ToolResult_62_Input AT %IB218 : keyence_iv3_ToolResult_62_Input_Layout;

        // Module keyence_iv3/ToolResult_63
        keyence_iv3_ToolResult_63_Input AT %IB198 : keyence_iv3_ToolResult_63_Input_Layout;

        // Module keyence_iv3/ToolResult_64
        keyence_iv3_ToolResult_64_Input AT %IB178 : keyence_iv3_ToolResult_64_Input_Layout;

        // Module keyence_iv3/ToolResult_7
        keyence_iv3_ToolResult_7_Input AT %IB1318 : keyence_iv3_ToolResult_7_Input_Layout;

        // Module keyence_iv3/ToolResult_8
        keyence_iv3_ToolResult_8_Input AT %IB1298 : keyence_iv3_ToolResult_8_Input_Layout;

        // Module keyence_iv3/ToolResult_9
        keyence_iv3_ToolResult_9_Input AT %IB1278 : keyence_iv3_ToolResult_9_Input_Layout;

        // Module keyence_sr_1000/BusyStatus
        keyence_sr_1000_BusyStatus_Input AT %IB1698 : keyence_sr_1000_BusyStatus_Input_Layout;

        // Module keyence_sr_1000/CompletionClearControl
        keyence_sr_1000_CompletionClearControl_Output AT %QB279 : keyence_sr_1000_CompletionClearControl_Output_Layout;

        // Module keyence_sr_1000/CompletionStatus
        keyence_sr_1000_CompletionStatus_Input AT %IB1697 : keyence_sr_1000_CompletionStatus_Input_Layout;

        // Module keyence_sr_1000/ErrorStatus
        keyence_sr_1000_ErrorStatus_Input AT %IB1696 : keyence_sr_1000_ErrorStatus_Input_Layout;

        // Module keyence_sr_1000/HandshakeAndGeneralErrorStatus
        keyence_sr_1000_HandshakeAndGeneralErrorStatus_Input AT %IB1699 : keyence_sr_1000_HandshakeAndGeneralErrorStatus_Input_Layout;

        // Module keyence_sr_1000/LatchAndErrorClearControl
        keyence_sr_1000_LatchAndErrorClearControl_Output AT %QB281 : keyence_sr_1000_LatchAndErrorClearControl_Output_Layout;

        // Module keyence_sr_1000/MatchingLevelAndTotalEvaluationGradeStatus
        keyence_sr_1000_MatchingLevelAndTotalEvaluationGradeStatus_Input AT %IB1686 : keyence_sr_1000_MatchingLevelAndTotalEvaluationGradeStatus_Input_Layout;

        // Module keyence_sr_1000/OperationInstructionControl
        keyence_sr_1000_OperationInstructionControl_Output AT %QB280 : keyence_sr_1000_OperationInstructionControl_Output_Layout;

        // Module keyence_sr_1000/OperationResultStatus
        keyence_sr_1000_OperationResultStatus_Input AT %IB1666 : keyence_sr_1000_OperationResultStatus_Input_Layout;

        // Module keyence_sr_1000/ParameterBank
        keyence_sr_1000_ParameterBank_Output AT %QB277 : keyence_sr_1000_ParameterBank_Output_Layout;

        // Module keyence_sr_1000/ResultData_128
        keyence_sr_1000_ResultData_128_Input AT %IB1530 : keyence_sr_1000_ResultData_128_Input_Layout;

        // Module keyence_sr_1000/TerminalStatus
        keyence_sr_1000_TerminalStatus_Input AT %IB1695 : keyence_sr_1000_TerminalStatus_Input_Layout;

        // Module keyence_sr_1000/UnstableReadStatus
        keyence_sr_1000_UnstableReadStatus_Input AT %IB1694 : keyence_sr_1000_UnstableReadStatus_Input_Layout;

        // Module keyence_sr_1000/UserData_128
        keyence_sr_1000_UserData_128_Output AT %QB147 : keyence_sr_1000_UserData_128_Output_Layout;

        // Module keyence_sr_750/BusyStatus
        keyence_sr_750_BusyStatus_Input AT %IB168 : keyence_sr_750_BusyStatus_Input_Layout;

        // Module keyence_sr_750/CompletionClearControl
        keyence_sr_750_CompletionClearControl_Output AT %QB132 : keyence_sr_750_CompletionClearControl_Output_Layout;

        // Module keyence_sr_750/CompletionStatus
        keyence_sr_750_CompletionStatus_Input AT %IB167 : keyence_sr_750_CompletionStatus_Input_Layout;

        // Module keyence_sr_750/ErrorStatus
        keyence_sr_750_ErrorStatus_Input AT %IB166 : keyence_sr_750_ErrorStatus_Input_Layout;

        // Module keyence_sr_750/HandshakeAndGeneralErrorStatus
        keyence_sr_750_HandshakeAndGeneralErrorStatus_Input AT %IB169 : keyence_sr_750_HandshakeAndGeneralErrorStatus_Input_Layout;

        // Module keyence_sr_750/LatchAndErrorClearControl
        keyence_sr_750_LatchAndErrorClearControl_Output AT %QB134 : keyence_sr_750_LatchAndErrorClearControl_Output_Layout;

        // Module keyence_sr_750/MatchingLevelAndTotalEvaluationGradeStatus
        keyence_sr_750_MatchingLevelAndTotalEvaluationGradeStatus_Input AT %IB156 : keyence_sr_750_MatchingLevelAndTotalEvaluationGradeStatus_Input_Layout;

        // Module keyence_sr_750/OperationInstructionControl
        keyence_sr_750_OperationInstructionControl_Output AT %QB133 : keyence_sr_750_OperationInstructionControl_Output_Layout;

        // Module keyence_sr_750/OperationResultStatus
        keyence_sr_750_OperationResultStatus_Input AT %IB136 : keyence_sr_750_OperationResultStatus_Input_Layout;

        // Module keyence_sr_750/ParameterBank
        keyence_sr_750_ParameterBank_Output AT %QB130 : keyence_sr_750_ParameterBank_Output_Layout;

        // Module keyence_sr_750/ResultData_128
        keyence_sr_750_ResultData_128_Input AT %IB0 : keyence_sr_750_ResultData_128_Input_Layout;

        // Module keyence_sr_750/TerminalStatus
        keyence_sr_750_TerminalStatus_Input AT %IB165 : keyence_sr_750_TerminalStatus_Input_Layout;

        // Module keyence_sr_750/UnstableReadStatus
        keyence_sr_750_UnstableReadStatus_Input AT %IB164 : keyence_sr_750_UnstableReadStatus_Input_Layout;

        // Module keyence_sr_750/UserData_128
        keyence_sr_750_UserData_128_Output AT %QB0 : keyence_sr_750_UserData_128_Output_Layout;
    END_VAR
END_CONFIGURATION

TYPE
    keyence_iv3_CommandControl_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %B1 : BYTE;
        Signals_9 AT %X2.0 : BOOL;
        Signals_10 AT %B3 : BYTE;
        Signals_11 AT %B4 : WORD;
        Signals_12 AT %B6 : WORD;
        Signals_13 AT %B8 : DWORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_CommandStatusBits_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %X0.7 : BOOL;
        Signals_8 AT %X1.0 : BOOL;
        Signals_9 AT %X1.1 : BOOL;
        Signals_10 AT %X1.2 : BOOL;
        Signals_11 AT %X1.6 : BOOL;
        Signals_12 AT %X1.7 : BOOL;
        Signals_13 AT %X2.0 : BOOL;
        Signals_14 AT %X2.1 : BOOL;
        Signals_15 AT %X2.2 : BOOL;
        Signals_16 AT %X2.3 : BOOL;
        Signals_17 AT %X2.4 : BOOL;
        Signals_18 AT %X2.5 : BOOL;
        Signals_19 AT %X2.7 : BOOL;
        Signals_20 AT %X3.0 : BOOL;
        Signals_21 AT %X3.4 : BOOL;
        Signals_22 AT %X3.5 : BOOL;
        Signals_23 AT %X3.6 : BOOL;
        Signals_24 AT %X3.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_DeviceResultBits_1_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
        Signals_5 AT %X0.5 : BOOL;
        Signals_6 AT %X0.6 : BOOL;
        Signals_7 AT %B1 : BYTE;
        Signals_8 AT %X2.0 : BOOL;
        Signals_9 AT %X2.1 : BOOL;
        Signals_10 AT %X2.2 : BOOL;
        Signals_11 AT %X2.3 : BOOL;
        Signals_12 AT %X2.4 : BOOL;
        Signals_13 AT %X2.5 : BOOL;
        Signals_14 AT %X2.6 : BOOL;
        Signals_15 AT %X2.7 : BOOL;
        Signals_16 AT %X3.0 : BOOL;
        Signals_17 AT %X3.1 : BOOL;
        Signals_18 AT %X3.2 : BOOL;
        Signals_19 AT %X3.3 : BOOL;
        Signals_20 AT %X3.4 : BOOL;
        Signals_21 AT %X3.5 : BOOL;
        Signals_22 AT %X3.6 : BOOL;
        Signals_23 AT %X3.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_DeviceResultBits_2_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %X2.0 : BOOL;
        Signals_2 AT %X2.1 : BOOL;
        Signals_3 AT %X2.2 : BOOL;
        Signals_4 AT %X2.3 : BOOL;
        Signals_5 AT %X2.4 : BOOL;
        Signals_6 AT %X2.5 : BOOL;
        Signals_7 AT %X2.6 : BOOL;
        Signals_8 AT %X2.7 : BOOL;
        Signals_9 AT %X3.0 : BOOL;
        Signals_10 AT %X3.1 : BOOL;
        Signals_11 AT %X3.2 : BOOL;
        Signals_12 AT %X3.3 : BOOL;
        Signals_13 AT %X3.4 : BOOL;
        Signals_14 AT %X3.5 : BOOL;
        Signals_15 AT %X3.6 : BOOL;
        Signals_16 AT %X3.7 : BOOL;
        Signals_17 AT %X4.0 : BOOL;
        Signals_18 AT %X4.1 : BOOL;
        Signals_19 AT %X4.2 : BOOL;
        Signals_20 AT %X4.3 : BOOL;
        Signals_21 AT %X4.4 : BOOL;
        Signals_22 AT %X4.5 : BOOL;
        Signals_23 AT %X4.6 : BOOL;
        Signals_24 AT %X4.7 : BOOL;
        Signals_25 AT %X5.0 : BOOL;
        Signals_26 AT %X5.1 : BOOL;
        Signals_27 AT %X5.2 : BOOL;
        Signals_28 AT %X5.3 : BOOL;
        Signals_29 AT %X5.4 : BOOL;
        Signals_30 AT %X5.5 : BOOL;
        Signals_31 AT %X5.6 : BOOL;
        Signals_32 AT %X5.7 : BOOL;
        Signals_33 AT %X6.0 : BOOL;
        Signals_34 AT %X6.1 : BOOL;
        Signals_35 AT %X6.2 : BOOL;
        Signals_36 AT %X6.3 : BOOL;
        Signals_37 AT %X6.4 : BOOL;
        Signals_38 AT %X6.5 : BOOL;
        Signals_39 AT %X6.6 : BOOL;
        Signals_40 AT %X6.7 : BOOL;
        Signals_41 AT %X7.0 : BOOL;
        Signals_42 AT %X7.1 : BOOL;
        Signals_43 AT %X7.2 : BOOL;
        Signals_44 AT %X7.3 : BOOL;
        Signals_45 AT %X7.4 : BOOL;
        Signals_46 AT %X7.5 : BOOL;
        Signals_47 AT %X7.6 : BOOL;
        Signals_48 AT %X7.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_DeviceStatistics_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : DWORD;
        Signals_5 AT %B12 : DWORD;
        Signals_6 AT %B16 : DWORD;
        Signals_7 AT %B20 : DWORD;
        Signals_8 AT %B24 : DWORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_DeviceStatusWords_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_PositionAdjustResult_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_1_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_10_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_11_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_12_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_13_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_14_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_15_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_16_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_17_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_18_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_19_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_2_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_20_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_21_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_22_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_23_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_24_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_25_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_26_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_27_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_28_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_29_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_3_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_30_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_31_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_32_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_33_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_34_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_35_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_36_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_37_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_38_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_39_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_4_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_40_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_41_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_42_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_43_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_44_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_45_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_46_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_47_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_48_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_49_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_5_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_50_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_51_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_52_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_53_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_54_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_55_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_56_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_57_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_58_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_59_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_6_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_60_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_61_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_62_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_63_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_64_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_7_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_8_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_iv3_ToolResult_9_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_BusyStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_CompletionClearControl_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_CompletionStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_ErrorStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_HandshakeAndGeneralErrorStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.6 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_LatchAndErrorClearControl_Output_Layout : STRUCT
        Signals_0 AT %X0.1 : BOOL;
        Signals_1 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_MatchingLevelAndTotalEvaluationGradeStatus_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_OperationInstructionControl_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_OperationResultStatus_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_ParameterBank_Output_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_ResultData_128_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : ARRAY[0..127] OF BYTE;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_TerminalStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.4 : BOOL;
        Signals_3 AT %X0.5 : BOOL;
        Signals_4 AT %X0.6 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_UnstableReadStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_1000_UserData_128_Output_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : ARRAY[0..127] OF BYTE;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_BusyStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_CompletionClearControl_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_CompletionStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_ErrorStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_HandshakeAndGeneralErrorStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.6 : BOOL;
        Signals_4 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_LatchAndErrorClearControl_Output_Layout : STRUCT
        Signals_0 AT %X0.1 : BOOL;
        Signals_1 AT %X0.7 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_MatchingLevelAndTotalEvaluationGradeStatus_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_OperationInstructionControl_Output_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_OperationResultStatus_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : WORD;
        Signals_5 AT %B10 : WORD;
        Signals_6 AT %B12 : WORD;
        Signals_7 AT %B14 : WORD;
        Signals_8 AT %B16 : WORD;
        Signals_9 AT %B18 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_ParameterBank_Output_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_ResultData_128_Input_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : WORD;
        Signals_2 AT %B4 : WORD;
        Signals_3 AT %B6 : WORD;
        Signals_4 AT %B8 : ARRAY[0..127] OF BYTE;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_TerminalStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.4 : BOOL;
        Signals_3 AT %X0.5 : BOOL;
        Signals_4 AT %X0.6 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_UnstableReadStatus_Input_Layout : STRUCT
        Signals_0 AT %X0.0 : BOOL;
        Signals_1 AT %X0.1 : BOOL;
        Signals_2 AT %X0.2 : BOOL;
        Signals_3 AT %X0.3 : BOOL;
        Signals_4 AT %X0.4 : BOOL;
    END_STRUCT;
END_TYPE

TYPE
    keyence_sr_750_UserData_128_Output_Layout : STRUCT
        Signals_0 AT %B0 : WORD;
        Signals_1 AT %B2 : ARRAY[0..127] OF BYTE;
    END_STRUCT;
END_TYPE
