NAMESPACE AXOpen.Components.Mitsubishi.Robotics
    TYPE
        HwIdentifiers : UINT
        (
            TZ535_PN_HwID :=	UINT#258,
            TZ535_PN_In_Out_64_byte_In_Out__64_byte_HwID :=	UINT#263,
            TZ535_PN_Rack_HwID :=	UINT#261,
            TZ535_PN_TZ535_PN_HwID :=	UINT#262,
            TZ535_PN_TZ535_PN_2D_TZ535_PNPROFINET_IO_HwID :=	UINT#264,
            TZ535_PN_TZ535_PN_profinet_HwID :=	UINT#257,
            TZ535_PN_TZ535_PN_profinet_Port_1_HwID :=	UINT#259,
            TZ535_PN_TZ535_PN_profinet_Port_2_HwID :=	UINT#260,
            plc_line_HwID :=	UINT#32,
            plc_line_Rail_0_HwID :=	UINT#265,
            plc_line_plc_line_HwID :=	UINT#48,
            plc_line_plc_line_CPU_display_1_HwID :=	UINT#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=	UINT#51,
            plc_line_plc_line_DP_interface_1_HwID :=	UINT#60,
            plc_line_plc_line_OPC_UA_1_HwID :=	UINT#117,
            plc_line_plc_line_profinet_x1_HwID :=	UINT#64,
            plc_line_plc_line_profinet_x1_Port_1_HwID :=	UINT#65,
            plc_line_plc_line_profinet_x1_Port_2_HwID :=	UINT#66,
            plc_line_plc_line_profinet_x2_HwID :=	UINT#72,
            plc_line_plc_line_profinet_x2_Port_3_HwID :=	UINT#73,
            plc_line_plc_line_virtual_communication_interface_HwID :=	UINT#135,
            profinet_plc_line_HwID :=	UINT#256,
    
            NONE := UINT#0
        );
    END_TYPE
END_NAMESPACE
