TYPE
	HwIdentifiers : WORD
	(
		PLC_LINE_Rail_0 :=	WORD#256,
		PLC_LINE :=	WORD#48,
		PLC_LINE_Card_reader_writer_1 :=	WORD#51,
		PLC_LINE_CPU_display_1 :=	WORD#54,
		PLC_LINE_OPC_UA_1 :=	WORD#117,
		PLC_LINE_PROFINET_interface_1 :=	WORD#64,
		PLC_LINE_PROFINET_interface_1_Port_1 :=	WORD#65,
		PLC_LINE_PROFINET_interface_1_Port_2 :=	WORD#66,
		PLC_LINE_PROFINET_interface_2 :=	WORD#72,
		PLC_LINE_PROFINET_interface_2_Port_1 :=	WORD#73,
		PLC_LINE_DP_interface_1 :=	WORD#60,
		PLC_LINE_PROFINET_interface_GBIT_3 :=	WORD#120,
		PLC_LINE_PROFINET_interface_GBIT_3_Port_1 :=	WORD#121,
		cmmtas_PN_IO_Interface :=	WORD#271,
		cmmtas_PN_IO_Interface_Port_1 :=	WORD#260,
		cmmtas_PN_IO_Interface_Port_2 :=	WORD#261,
		cmmtas_CMMT_AS_MP :=	WORD#272,
		cmmtas_DO_SERVO_1_Module_Access_Point :=	WORD#264,
		cmmtas_DO_SERVO_1_Siemens_telegram_111_PZD_12_12 :=	WORD#265,
		cmmtas_DO_SERVO_1_Siemens_telegram_750_PZD_4_1 :=	WORD#266,
		cmmtas_Siemens_telegram_111_PZD_12_12 :=	WORD#265,
		cmmtas_Siemens_telegram_750_PZD_4_1 :=	WORD#266,
		NONE:= WORD#0
	);
END_TYPE
