TYPE
	HwIdentifiers : ULINT
	(
		PLC_LINE_Rail_0 :=	ULINT#256,
		PLC_LINE_PLC_LINE :=	ULINT#48,
		PLC_LINE_Card_reader_writer_1 :=	ULINT#51,
		PLC_LINE_CPU_display_1 :=	ULINT#54,
		PLC_LINE_OPC_UA_1 :=	ULINT#117,
		PLC_LINE_PROFINET_interface_1 :=	ULINT#64,
		PLC_LINE_Port_1 :=	ULINT#65,
		PLC_LINE_Port_2 :=	ULINT#66,
		PLC_LINE_PROFINET_interface_2 :=	ULINT#72,
		PLC_LINE_DP_interface_1 :=	ULINT#60,
		PLC_LINE_PROFINET_interface_GBIT_3 :=	ULINT#120,
		cmmtas_test_PN_IO_Interface :=	ULINT#271,
		cmmtas_test_Port_1 :=	ULINT#260,
		cmmtas_test_Port_2 :=	ULINT#261,
		cmmtas_test_CMMT_AS_MP :=	ULINT#272,
		cmmtas_test_Module_Access_Point :=	ULINT#264,
		cmmtas_test_Siemens_telegram_111_PZD_12_12 :=	ULINT#265,
		cmmtas_test_Siemens_telegram_750_PZD_4_1 :=	ULINT#266,
		cmmtas_docu_PN_IO_Interface :=	ULINT#267,
		cmmtas_docu_Port_1 :=	ULINT#273,
		cmmtas_docu_Port_2 :=	ULINT#274,
		cmmtas_docu_CMMT_AS_MP :=	ULINT#275,
		cmmtas_docu_Module_Access_Point :=	ULINT#279,
		cmmtas_docu_Siemens_telegram_111_PZD_12_12 :=	ULINT#276,
		cmmtas_docu_Siemens_telegram_750_PZD_4_1 :=	ULINT#277,
		NONE:= ULINT#0
	);
END_TYPE
