TYPE
	HwIdentifiers : WORD
	(
		PLC_LINE_Rail_0 :=	WORD#256,
		PLC_LINE_PLC_LINE :=	WORD#48,
		PLC_LINE_Card_reader_writer_1 :=	WORD#51,
		PLC_LINE_CPU_display_1 :=	WORD#54,
		PLC_LINE_OPC_UA_1 :=	WORD#117,
		PLC_LINE_PROFINET_interface_1 :=	WORD#64,
		PLC_LINE_Port_1 :=	WORD#65,
		PLC_LINE_Port_2 :=	WORD#66,
		PLC_LINE_PROFINET_interface_2 :=	WORD#72,
		PLC_LINE_DP_interface_1 :=	WORD#60,
		PLC_LINE_PROFINET_interface_GBIT_3 :=	WORD#120,
		ST3_indradrive_Rack :=	WORD#336,
		ST3_indradrive_ST3_indradrive :=	WORD#337,
		ST3_indradrive_PN_IO :=	WORD#338,
		ST3_indradrive_Port_1_RJ45 :=	WORD#339,
		ST3_indradrive_Port_2_RJ45 :=	WORD#340,
		ST3_indradrive_DAP_1 :=	WORD#341,
		ST3_indradrive_ID_FMod_NotUsed :=	WORD#342,
		ST3_indradrive_ID_PaCh_5Words :=	WORD#258,
		ST3_indradrive_ID_InMod_9Words :=	WORD#262,
		ST3_indradrive_ID_OutMod_13Words :=	WORD#259,
		cmmtas_test_PN_IO_Interface :=	WORD#271,
		cmmtas_test_Port_1 :=	WORD#260,
		cmmtas_test_Port_2 :=	WORD#261,
		cmmtas_test_CMMT_AS_MP :=	WORD#272,
		cmmtas_test_Module_Access_Point :=	WORD#264,
		cmmtas_test_Siemens_telegram_111_PZD_12_12 :=	WORD#265,
		cmmtas_test_Siemens_telegram_750_PZD_4_1 :=	WORD#266,
		NONE:= WORD#0
	);
END_TYPE
