NAMESPACE AXOpen.Components.Festo.Drives
    TYPE
        {S7.extern=ReadWrite}
        {#ix-attr:[Container(Layout.Wrap)]}
        Outputs : STRUCT
	        festo_cmmtas_DoServo_SiemensTelegram111_PZD_12_12_Output AT %B0 : festo_cmmtas_DoServo_SiemensTelegram111_PZD_12_12_Output_Layout;

	        festo_cmmtas_DoServo_SiemensTelegram750_PZD_4_1_Output AT %B24 : festo_cmmtas_DoServo_SiemensTelegram750_PZD_4_1_Output_Layout;

        END_STRUCT;
    END_TYPE
END_NAMESPACE

