NAMESPACE AXOpen.Components.Siem.Communication
    TYPE
        HwIdentifiers : UINT
        (
            et200sp_HwID :=UINT#258,
            et200sp_CpPtp_CM_PtP_V2_0_HwID :=UINT#264,
            et200sp_Rack_HwID :=UINT#261,
            et200sp_Server_module_V1_1_Server_module_V1_1_0_bytes_HwID :=UINT#263,
            et200sp_et200sp_HwID :=UINT#262,
            et200sp_et200sp_IM_155_6_PN_ST_V4_2_HwID :=UINT#265,
            et200sp_et200sp_Port_1_HwID :=UINT#259,
            et200sp_et200sp_Port_2_HwID :=UINT#260,
            et200sp_et200sp_profinet_HwID :=UINT#257,
            plc_line_HwID :=UINT#32,
            plc_line_Rail_0_HwID :=UINT#266,
            plc_line_plc_line_HwID :=UINT#48,
            plc_line_plc_line_CPU_display_1_HwID :=UINT#54,
            plc_line_plc_line_Card_reader_writer_1_HwID :=UINT#51,
            plc_line_plc_line_DP_interface_1_HwID :=UINT#60,
            plc_line_plc_line_OPC_UA_1_HwID :=UINT#117,
            plc_line_plc_line_Virtual_communication_interface_HwID :=UINT#135,
            plc_line_plc_line_profinet_x1_HwID :=UINT#64,
            plc_line_plc_line_profinet_x1_Port_1_HwID :=UINT#65,
            plc_line_plc_line_profinet_x1_Port_2_HwID :=UINT#66,
            plc_line_plc_line_profinet_x2_HwID :=UINT#72,
            plc_line_plc_line_profinet_x2_Port_3_HwID :=UINT#73,
            profinet_plc_line_HwID :=UINT#256,
    
            NONE := UINT#0
        );
    END_TYPE
END_NAMESPACE
