<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageId>AXOpen.VisualComposer</PackageId>
		<RootNamespace>AXOpen.VisualComposer</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" /> 
		<PackageReference Include="Inxton.Operon" />				
		<PackageReference Include="AXSharp.Abstractions" />
		<PackageReference Include="AXSharp.Connector" />
		<PackageReference Include="AXSharp.Presentation.Blazor" />
		<PackageReference Include="AXSharp.Presentation.Blazor.Controls" />
		<PackageReference Include="AXOpen.KristofferStrube.Blazor.SVGEditor" />
	</ItemGroup>			
</Project>
