name: app-test

on:
  push:
    branches: [ "504-app-test-workflow" ]
    paths:
     - 'src/**'
     - 'cake/**'
     - '.github/**'  
     - 'scripts/**'  
  workflow_dispatch:

jobs:
  run-app-test:
    runs-on: [self-hosted, Windows, X64, AX, APP] 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'   
                   
    - name: "Build  script"  
      run: dotnet build cake/Build.csproj
                       
    - name: "Run build script"
      env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}
          GH_USER : ${{ secrets.GH_USER }}
      run: dotnet run --project cake/Build.csproj --do-test --do-pack --test-level 3 --do-publish --apps-run
