name: app-test

on:
  push:
    branches: [ "504-app-test-workflow" ]
    paths:
     - 'src/**'
     - 'cake/**'
     - '.github/**'  
     - 'scripts/**'  
  workflow_dispatch:

jobs:
  run-app-test:
    runs-on: [self-hosted, Windows, X64, APP] 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the repository

    - name: Run app test PowerShell script
      run: |
        try 
        {
            ./scripts/app-test.ps1 2>&1 | ForEach-Object { Write-Host $_ }
        }
        catch 
        {
            Write-Error "An unexpected error occurred: $_"
        }
      shell: powershell