name: dev
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

on:
#  push:
#    branches: [ "dev" ]
#    paths:
#     - 'src/**'
#     - 'cake/**'
#     - '.github/**'  
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Set to 'true' to publish packages"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: [self-hosted, Windows, X64, L2, AX]  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'   

    - name: "Build  script"  
      run: dotnet build cake/Build.csproj
      shell: pwsh
                       
    - name: "Run build script"
      env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}
          GH_USER : ${{ secrets.GH_USER }}
      run: |
        dotnet run --project cake/Build.csproj --do-test --do-pack --test-level 2
        "TEST_EXIT_CODE=$LASTEXITCODE" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
      shell: pwsh
      
    - name: "Publish packages"
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USER: ${{ secrets.GH_USER }}
      run: |
        dotnet run --project cake/Build.csproj --do-publish-only --do-publish --do-publish-release
        "PACK_EXIT_CODE=$LASTEXITCODE" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
      shell: pwsh

  docs:
    needs: build
    runs-on: [self-hosted, Windows, X64, L2, AX]
    steps:
    - name: Generate ctrl API metadata (ixd)
      shell: pwsh
      run: .\scripts\_invoke_ixd.ps1

    - name: Docfx metadata
      shell: pwsh
      run: dotnet docfx metadata .\docfx\docfx.json

    - name: Docfx build
      shell: pwsh
      run: dotnet docfx build .\docfx\docfx.json --output .\docs\

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy:
    needs: docs
    runs-on: [self-hosted, Windows, X64, L2, AX]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
