name: single_app_run
on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Select library folder"
        required: true
        default: "template.axolibrary"
        type: choice
        options:
          - abstractions
          - components.abb.robotics
          - components.abstractions
          - components.balluff.identification
          - components.cognex.vision
          - components.desoutter.tightening
          - components.drives
          - components.elements
          - components.festo.drives
          - components.kuka.robotics
          - components.keyence.vision
          - components.mitsubishi.robotics
          - components.pneumatics
          - components.rexroth.drives
          - components.rexroth.press
          - components.robotics
          - components.siem.identification
          - components.ur.robotics
          - core
          - data
          - inspectors
          - integrations
          - io
          - probers
          - simatic1500
          - template.axolibrary
          - timers
          - utils

jobs:
  app-run-manual-with-selected-folder:
    runs-on: [self-hosted, Windows, X64, L3, AX, APP]  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'   

    - name: Get Branch Name
      shell: pwsh
      run: |
        if ($env:GITHUB_REF -like "refs/pull/*") {
          $BRANCH_NAME = "${{ github.event.pull_request.head.ref }}"
        } else {
          $BRANCH_NAME = $env:GITHUB_REF -replace 'refs/heads/', ''
        }
        Write-Host "Triggered on branch: $BRANCH_NAME"
        "BRANCH_NAME=$BRANCH_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Get Short Commit SHA
      shell: pwsh
      run: |
          $currentSHA = git rev-parse --short HEAD
          "CURRENT_SHA=$currentSHA" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8  

    - name: Setup
      shell: pwsh
      run: |
        "TEST_EXIT_CODE=123" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

    - name: Print and store library folder
      shell: pwsh
      run: |
        $APP_FOLDER = "${{ inputs.folder }}"
        Write-Host "Selected folder: $APP_FOLDER"
        "APP_FOLDER=$APP_FOLDER" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: "Build cake"  
      run: dotnet build cake/Build.csproj
                       
    - name: "Run cake with single app"
      continue-on-error: true     
      env:
        GH_TOKEN : ${{ secrets.GH_TOKEN }}
        GH_USER : ${{ secrets.GH_USER }}
      run: |
        dotnet run --project cake/Build.csproj --skip-build --apps-run --single-app-run-folder-name $env:APP_FOLDER
        $LASTEXITCODE = 1    
        "TEST_EXIT_CODE=$LASTEXITCODE" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

    - name: Display workflow details in Summary
      shell: pwsh
      run: |
        if($env:TEST_EXIT_CODE -eq "123")
        {
          $TEST_RESULT = "SKIPPED"
        }
        elseif($env:TEST_EXIT_CODE -eq "0")
        {
          $TEST_RESULT = "PASSED"
        }
        else
        {
          $TEST_RESULT = "FAILED"
        }
        "### Runner name: $env:RUNNER_NAME ::: Branch name: $env:BRANCH_NAME ::: Library folder: $env:APP_FOLDER ::: Commit SHA: $env:CURRENT_SHA ::: Test result: $TEST_RESULT"  | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8

    - name: Evaluate final result
      shell: pwsh
      run: |
          if($env:TEST_EXIT_CODE -eq "123")
          {
            echo "Tests skipped."
          }
          elseif($env:TEST_EXIT_CODE -eq "0")
          {
            echo "Tests passed."
          }
          else
          {
            echo "Tests failed."
            Exit 1
          }      

