CLASS hierarchy_0
    VAR PUBLIC
                                                            {#ix-set:AttributeName = "Member L0 1 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_1   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 2 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_2   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 3 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_3   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 4 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_4   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 5 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_5   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 6 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_6   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 7 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_7   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 8 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_8   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 9 "} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_9   :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 10"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_10  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 12"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_12  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 13"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_13  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 14"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_14  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 15"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_15  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 16"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_16  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 17"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_17  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 18"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_18  :     full_of_primitives;  {#ix-set:AttributeName = "Member L0 19"} {#ix-attr:[Container(Layout.Wrap)]} {#ix-attr:[Group(GroupLayout.GroupBox)]}
        item_member_property_19  :     full_of_primitives;  
    END_VAR    
END_CLASS